<?php
/**
 * Template Name: Single Anchor Up Promotion
 * Modern Dashboard Template for displaying a single Anchor Up Promotion
 */

// Promotions are allowed on this site - no access checks needed

global $post;
$post_id = $post->ID;

// Call acf_form_head() early to handle form submissions - must be before get_header()
if (function_exists('acf_form_head')) {
    acf_form_head();
}

// Get all custom fields
$promotion_header_image = get_field('promotion_header_image', $post_id);
$promotion_description = get_field('promotion_description', $post_id);
$start_store_sign_up_date = get_field('start_store_sign_up_date', $post_id);
$end_store_sign_up_date = get_field('end_store_sign_up_date', $post_id);
$promotion_start_date = get_field('promotion_start_date', $post_id);
$promotion_end_date = get_field('promotion_end_date', $post_id);
$marketing_start_date = get_field('marketing_to_anchor_up_stores_start_date', $post_id);
$setup_video_url = get_field('setup_video_demonstration', $post_id);
$whats_in_the_box = get_field('whats_in_the_box', $post_id);
$understanding_file = get_field('understanding', $post_id);
$agreement_form = get_field('agreement_form_selection', $post_id);
$assets = get_field('digital_assets', $post_id);
$anchor_up_featured_banner = get_field('anchor_up_featured_banner', $post_id);
$anchor_up_featured_banner_link = get_field('anchor_up_featured_banner_link', $post_id);
$anchor_up_homepage_featured_video = get_field('anchor_up_homepage_featured_video', $post_id);
$local_christian_find_store_text = get_field('local_christian_find_a_bookstore_near_me_promotional_text', $post_id);
$local_christian_promotional_long_text = get_field('local_christian_bookstore_promotional_long_text', $post_id);
$local_christian_hero_banner = get_field('local_christian_bookstore_com_hero_banner_during_promotion_period', $post_id);

// Get store ID
$store_id = '';
if (class_exists('\STW\AnchorUp\AnchorUp')) {
    $store = \STW\AnchorUp\AnchorUp::isAnchorUpAdmin(true);
    if ($store && method_exists($store, 'autonumber')) {
        $store_id = $store->autonumber;
    } else {
        $store_id = \STW\AnchorUp\AnchorUp::getAnchorUpAutoGeneratedStoreId($store);
    }
}

// Get submission status
$promotion_submission_post_id = anchor_up_promotion_get_submission_from_account_and_promotion($post_id);

get_header();
?>

<div class="min-h-screen">
    <!-- Hero Section -->
    <?php if ($promotion_header_image) { ?>
        <div class="relative w-full h-96 md:h-[500px] overflow-hidden">
            <img src="<?php echo esc_url($promotion_header_image); ?>" 
                 alt="<?php echo esc_attr(get_the_title()); ?>" 
                 class="w-full h-full object-cover">
            <div class="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent"></div>
            <div class="absolute bottom-0 left-0 right-0 p-8 md:p-12">
                <div class="flex items-end justify-between flex-wrap gap-4">
                    <div>
                        <h1 class="text-4xl md:text-6xl font-bold text-white mb-4 drop-shadow-lg">
                            <?php the_title(); ?>
                        </h1>
                        <?php if ($promotion_start_date && $promotion_end_date) { ?>
                            <div class="flex flex-wrap gap-4 text-white text-lg">
                                <span class="bg-blue-600/80 px-4 py-2 rounded-lg backdrop-blur-sm">
                                    📅 <?php echo esc_html($promotion_start_date); ?> - <?php echo esc_html($promotion_end_date); ?>
                                </span>
                            </div>
                        <?php } ?>
                    </div>
                    <?php
                    // Check if we're within the sign-up date range
                    $is_within_signup_period = false;
                    if ($start_store_sign_up_date && $end_store_sign_up_date) {
                        $today = strtotime(date('Ymd'));
                        $signup_start = strtotime($start_store_sign_up_date);
                        $signup_end = strtotime($end_store_sign_up_date);
                        $is_within_signup_period = ($today >= $signup_start && $today <= $signup_end);
                    }
                    
                    if ($is_within_signup_period) {
                    ?>
                        <button onclick="openSignupModal()" 
                                class="inline-flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-6 py-3 rounded-lg font-semibold text-lg transition-all shadow-lg hover:shadow-xl backdrop-blur-sm">
                            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                            </svg>
                            Sign Up for This Promotion
                        </button>
                    <?php } ?>
                </div>
            </div>
        </div>
    <?php } else { ?>
        <div class="bg-gradient-to-r from-blue-600 to-purple-600 text-white py-16 px-4">
            <div class="max-w-7xl mx-auto text-center">
                <h1 class="text-4xl md:text-6xl font-bold mb-4"><?php the_title(); ?></h1>
                <?php if ($promotion_start_date && $promotion_end_date) { ?>
                    <p class="text-xl md:text-2xl"><?php echo esc_html($promotion_start_date); ?> - <?php echo esc_html($promotion_end_date); ?></p>
                <?php } ?>
                <?php
                // Check if we're within the sign-up date range
                $is_within_signup_period = false;
                if ($start_store_sign_up_date && $end_store_sign_up_date) {
                    $today = strtotime(date('Ymd'));
                    $signup_start = strtotime($start_store_sign_up_date);
                    $signup_end = strtotime($end_store_sign_up_date);
                    $is_within_signup_period = ($today >= $signup_start && $today <= $signup_end);
                }
                
                if ($is_within_signup_period) {
                ?>
                    <div class="mt-6">
                        <button onclick="openSignupModal()" 
                                class="inline-flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-6 py-3 rounded-lg font-semibold text-lg transition-all shadow-lg hover:shadow-xl">
                            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                            </svg>
                            Sign Up for This Promotion
                        </button>
                    </div>
                <?php } ?>
            </div>
        </div>
    <?php } ?>

    <!-- Breadcrumbs -->
    <div class="bg-white border-b border-gray-200">
        <div class="max-w-7xl mx-auto px-4 py-4">
            <nav class="flex items-center space-x-2 text-sm" aria-label="Breadcrumb">
                <a href="<?php echo esc_url(home_url('/')); ?>" 
                   class="text-gray-500 hover:text-blue-600 transition-colors">
                    Home
                </a>
                <svg class="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                </svg>
                <a href="<?php echo esc_url(get_post_type_archive_link('anchor-up-promotion')); ?>" 
                   class="text-gray-500 hover:text-blue-600 transition-colors">
                    Anchor-Up Promotions
                </a>
                <svg class="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                </svg>
                <span class="text-gray-900 font-medium" aria-current="page">
                    <?php the_title(); ?>
                </span>
            </nav>
        </div>
    </div>

    <div class="max-w-7xl mx-auto px-4 py-8 md:py-12">
        <!-- Welcome Dashboard Section -->
        <div class="bg-white rounded-2xl shadow-xl p-6 md:p-8 mb-8 border border-gray-100">
            <div class="flex items-center gap-3 mb-6">
                <div class="w-12 h-12 bg-blue-600 rounded-full flex items-center justify-center">
                    <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                    </svg>
                </div>
                <h2 class="text-2xl md:text-3xl font-bold text-gray-900">Welcome to Your Promotion Dashboard</h2>
            </div>
            
            <?php if ($promotion_description) { ?>
                <div class="mb-6">
                    <h3 class="text-xl md:text-2xl font-bold text-gray-900 mb-4">About this Promotion</h3>
                    <div class="prose prose-lg max-w-none">
                        <?php echo wp_kses_post($promotion_description); ?>
                    </div>
                </div>
            <?php } ?>

            <!-- Key Information Cards -->
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
                <?php if ($start_store_sign_up_date) { ?>
                    <div class="bg-gradient-to-br from-blue-50 to-blue-100 rounded-xl p-5 border border-blue-200">
                        <div class="flex items-center gap-3 mb-2">
                            <span class="text-2xl">📝</span>
                            <h3 class="font-semibold text-gray-900">Store Sign Up Start</h3>
                        </div>
                        <p class="text-gray-700 text-lg font-medium"><?php echo esc_html($start_store_sign_up_date); ?></p>
                    </div>
                <?php } ?>
                
                <?php if ($end_store_sign_up_date) { ?>
                    <div class="bg-gradient-to-br from-purple-50 to-purple-100 rounded-xl p-5 border border-purple-200">
                        <div class="flex items-center gap-3 mb-2">
                            <span class="text-2xl">⏰</span>
                            <h3 class="font-semibold text-gray-900">Store Sign Up End</h3>
                        </div>
                        <p class="text-gray-700 text-lg font-medium"><?php echo esc_html($end_store_sign_up_date); ?></p>
                    </div>
                <?php } ?>
                
                <?php if ($promotion_start_date) { ?>
                    <div class="bg-gradient-to-br from-green-50 to-green-100 rounded-xl p-5 border border-green-200">
                        <div class="flex items-center gap-3 mb-2">
                            <span class="text-2xl">🚀</span>
                            <h3 class="font-semibold text-gray-900">Promotion Start</h3>
                        </div>
                        <p class="text-gray-700 text-lg font-medium"><?php echo esc_html($promotion_start_date); ?></p>
                    </div>
                <?php } ?>
                
                <?php if ($promotion_end_date) { ?>
                    <div class="bg-gradient-to-br from-orange-50 to-orange-100 rounded-xl p-5 border border-orange-200">
                        <div class="flex items-center gap-3 mb-2">
                            <span class="text-2xl">🏁</span>
                            <h3 class="font-semibold text-gray-900">Promotion End</h3>
                        </div>
                        <p class="text-gray-700 text-lg font-medium"><?php echo esc_html($promotion_end_date); ?></p>
                    </div>
                <?php } ?>
            </div>
        </div>

        <!-- Setup Video Section -->
        <?php if ($setup_video_url) { ?>
            <div id="setup-video" class="bg-white rounded-2xl shadow-xl p-6 md:p-8 mb-8 border border-gray-100">
                <div class="flex items-center gap-3 mb-6">
                    <div class="w-12 h-12 bg-red-600 rounded-full flex items-center justify-center">
                        <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z"></path>
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                        </svg>
                    </div>
                    <h2 class="text-2xl md:text-3xl font-bold text-gray-900">Setup Video Demonstration</h2>
                </div>
                <div class="aspect-video rounded-xl overflow-hidden shadow-lg">
                    <iframe class="w-full h-full" 
                            src="https://www.youtube.com/embed/<?php echo anchor_up_convert_youtube_url_to_iframe_url($setup_video_url); ?>?rel=0" 
                            frameborder="0" 
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
                            allowfullscreen>
                    </iframe>
                </div>
            </div>
        <?php } ?>

        <!-- Homepage Featured Video -->
        <?php if ($anchor_up_homepage_featured_video) { ?>
            <div class="bg-white rounded-2xl shadow-xl p-6 md:p-8 mb-8 border border-gray-100">
                <h2 class="text-2xl md:text-3xl font-bold text-gray-900 mb-6">Homepage Featured Video</h2>
                <div class="aspect-video rounded-xl overflow-hidden shadow-lg">
                    <iframe class="w-full h-full" 
                            src="https://www.youtube.com/embed/<?php echo anchor_up_convert_youtube_url_to_iframe_url($anchor_up_homepage_featured_video); ?>?rel=0" 
                            frameborder="0" 
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
                            allowfullscreen>
                    </iframe>
                </div>
            </div>
        <?php } ?>

        <!-- What's in the Box Section -->
        <?php if ($whats_in_the_box) { ?>
            <div class="bg-white rounded-2xl shadow-xl p-6 md:p-8 mb-8 border border-gray-100">
                <div class="flex items-center gap-3 mb-6">
                    <div class="w-12 h-12 bg-purple-600 rounded-full flex items-center justify-center">
                        <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"></path>
                        </svg>
                    </div>
                    <h2 class="text-2xl md:text-3xl font-bold text-gray-900">What's in the Box</h2>
                </div>
                <div class="prose prose-lg max-w-none">
                    <?php echo wp_kses_post($whats_in_the_box); ?>
                </div>
            </div>
        <?php } ?>

        <!-- Understanding Document -->
        <?php if ($understanding_file) { ?>
            <div class="bg-white rounded-2xl shadow-xl p-6 md:p-8 mb-8 border border-gray-100">
                <h2 class="text-2xl md:text-3xl font-bold text-gray-900 mb-6">Understanding Document</h2>
                <a href="<?php echo esc_url($understanding_file); ?>" 
                   target="_blank" 
                   class="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg font-semibold transition-colors shadow-md hover:shadow-lg">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                    </svg>
                    Download Understanding Document
                </a>
            </div>
        <?php } ?>

        <!-- Agreement Form -->
        <?php if ($agreement_form) { ?>
            <div class="bg-white rounded-2xl shadow-xl p-6 md:p-8 mb-8 border border-gray-100">
                <h2 class="text-2xl md:text-3xl font-bold text-gray-900 mb-6">Agreement Form</h2>
                <?php 
                if (function_exists('wpcf7_contact_form')) {
                    echo do_shortcode('[contact-form-7 id="' . $agreement_form->ID . '"]');
                } else {
                    echo '<p class="text-gray-600">Form will be displayed here.</p>';
                }
                ?>
            </div>
        <?php } ?>

        <!-- Sign Up For This Promotion Section -->
        <div id="sign-up-promotion" class="bg-white rounded-2xl shadow-xl p-6 md:p-8 mb-8 border border-gray-100">
            <div class="flex items-center gap-3 mb-6">
                <div class="w-12 h-12 bg-emerald-600 rounded-full flex items-center justify-center">
                    <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                    </svg>
                </div>
                <h2 class="text-2xl md:text-3xl font-bold text-gray-900">Sign Up For This Promotion</h2>
            </div>

            <?php
            // Check if we're within the sign-up date range
            $is_within_signup_period = false;
            if ($start_store_sign_up_date && $end_store_sign_up_date) {
                $today = strtotime(date('Ymd'));
                $signup_start = strtotime($start_store_sign_up_date);
                $signup_end = strtotime($end_store_sign_up_date);
                $is_within_signup_period = ($today >= $signup_start && $today <= $signup_end);
            }
            
            if ($is_within_signup_period) {
                // Check if user has already signed up for this promotion
                $existing_signup_id = null;
                if (class_exists('\STW\AnchorUp\AnchorUp')) {
                    $anchor_account_number = \STW\AnchorUp\AnchorUp::getAnchorAccountNumber();
                    if ($anchor_account_number) {
                        $signup_query = new WP_Query(array(
                            'post_type' => 'promo-signup',
                            'posts_per_page' => 1,
                            'meta_query' => array(
                                'relation' => 'AND',
                                array(
                                    'key' => 'specific_signup_anchor_customer_number',
                                    'value' => $anchor_account_number,
                                    'compare' => '=',
                                ),
                                array(
                                    'key' => 'specific_signup_promotion_relationship',
                                    'value' => $post_id,
                                    'compare' => '=',
                                ),
                            ),
                            'fields' => 'ids',
                        ));
                        
                        if ($signup_query->have_posts()) {
                            $existing_signup_id = $signup_query->posts[0];
                        }
                        wp_reset_postdata();
                    }
                }
            ?>
                <div class="text-center py-8">
                    <p class="text-gray-700 mb-6">Sign up to participate in this promotion. Your information will be pre-filled automatically.</p>
                    <button onclick="openSignupModal()" 
                            class="inline-flex items-center gap-2 bg-gradient-to-r from-emerald-600 to-green-600 hover:from-emerald-700 hover:to-green-700 text-white px-8 py-4 rounded-lg font-semibold text-lg transition-all shadow-lg hover:shadow-xl">
                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                        </svg>
                        <?php echo $existing_signup_id ? "Update" : "Sign Up"; ?> for This Promotion
                    </button>
                </div>
            <?php
            } else {
            ?>
                <div class="text-center py-8">
                    <div class="bg-gray-100 rounded-lg p-6 inline-block">
                        <p class="text-gray-600 text-lg font-semibold">Sign Up Promotion Window has Ended</p>
                        <?php if ($start_store_sign_up_date && $end_store_sign_up_date) { ?>
                            <p class="text-gray-500 text-sm mt-2">Sign-up period: <?php echo esc_html($start_store_sign_up_date); ?> - <?php echo esc_html($end_store_sign_up_date); ?></p>
                        <?php } ?>
                    </div>
                </div>
            <?php
            }
            ?>
        </div>

        <!-- Digital Assets Section -->
        <div id="digital-assets" class="bg-white rounded-2xl shadow-xl p-6 md:p-8 mb-8 border border-gray-100">
            <div class="flex items-center gap-3 mb-6">
                <div class="w-12 h-12 bg-indigo-600 rounded-full flex items-center justify-center">
                    <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"></path>
                    </svg>
                </div>
                <h2 class="text-2xl md:text-3xl font-bold text-gray-900">Digital Assets</h2>
            </div>

            <?php
            if ($assets) {
                // Sort assets by date_to_share
                function compare_assets($a, $b) {
                    $date_a = isset($a['date_to_share']) ? $a['date_to_share'] : '';
                    $date_b = isset($b['date_to_share']) ? $b['date_to_share'] : '';
                    return strtotime($date_a) - strtotime($date_b);
                }
                usort($assets, 'compare_assets');
            ?>
                <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    <?php foreach ($assets as $i => $asset) {
                        $digital_channel = isset($asset['digital_channel']) ? $asset['digital_channel'] : '';
                        $digital_file = isset($asset['digital_file']) ? $asset['digital_file'] : '';
                        $suggested_text = isset($asset['suggested_text']) ? $asset['suggested_text'] : '';
                        $date_to_share = isset($asset['date_to_share']) ? $asset['date_to_share'] : '';
                        $date_to_remove = isset($asset['date_to_remove']) ? $asset['date_to_remove'] : '';
                        $custom_css = isset($asset['custom_css']) ? $asset['custom_css'] : '';
                        $digital_file_name_override = isset($asset['digital_file_name_override']) ? $asset['digital_file_name_override'] : '';
                        $description = isset($asset['description']) ? $asset['description'] : '';
                        $is_form = isset($asset['is_this_digital_asset_a_form']) ? $asset['is_this_digital_asset_a_form'] : false;

                        $file_ext = pathinfo($digital_file, PATHINFO_EXTENSION);
                        $file_name = $digital_file_name_override ? $digital_file_name_override : (get_the_title() . '-' . $digital_channel . '-' . $date_to_share . '.' . $file_ext);
                        
                        $is_image = in_array(strtolower($file_ext), ['jpg', 'jpeg', 'png', 'gif', 'webp']);
                    ?>
                        <div class="bg-gradient-to-br from-gray-50 to-white rounded-xl p-6 border border-gray-200 hover:shadow-lg transition-all duration-300 <?php echo esc_attr($custom_css); ?>">
                            <div class="flex items-start justify-between mb-4">
                                <div>
                                    <h3 class="text-lg font-bold text-gray-900 mb-1">
                                        <?php echo $digital_file_name_override ? esc_html($digital_file_name_override) : esc_html($digital_channel . ' Asset ' . ($i + 1)); ?>
                                    </h3>
                                    <div class="flex items-center gap-2 text-sm text-gray-600">
                                        <span class="bg-blue-100 text-blue-800 px-2 py-1 rounded"><?php echo esc_html($digital_channel); ?></span>
                                        <?php if ($date_to_share) { ?>
                                            <span class="text-gray-500">📅 <?php echo esc_html($date_to_share); ?></span>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>

                            <?php if ($is_image && $digital_file) { ?>
                                <div class="mb-4 rounded-lg overflow-hidden bg-gray-100">
                                    <img src="<?php echo esc_url($digital_file); ?>" 
                                         alt="<?php echo esc_attr($digital_file_name_override ?: $digital_channel); ?>" 
                                         class="w-full h-48 object-cover">
                                </div>
                            <?php } ?>

                            <?php if ($description) { ?>
                                <p class="text-sm text-gray-700 mb-4"><?php echo wp_kses_post($description); ?></p>
                            <?php } ?>

                            <?php if ($suggested_text) { ?>
                                <div class="bg-blue-50 rounded-lg p-4 mb-4">
                                    <p class="text-xs font-semibold text-blue-900 mb-2">Suggested Text:</p>
                                    <p class="text-sm text-gray-700"><?php echo wp_kses_post($suggested_text); ?></p>
                                </div>
                            <?php } ?>

                            <a href="<?php echo esc_url($digital_file); ?>" 
                               download="<?php echo esc_attr($file_name); ?>"
                               target="_blank"
                               class="inline-flex items-center gap-2 w-full justify-center bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white px-4 py-3 rounded-lg font-semibold transition-all shadow-md hover:shadow-lg">
                                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                                </svg>
                                Download Asset
                            </a>

                            <?php if ($date_to_remove) { ?>
                                <p class="text-xs text-gray-500 mt-2 text-center">Remove: <?php echo esc_html($date_to_remove); ?></p>
                            <?php } ?>
                        </div>
                    <?php } ?>
                </div>
            <?php } else { ?>
                <div class="text-center py-12">
                    <svg class="w-16 h-16 text-gray-400 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"></path>
                    </svg>
                    <h3 class="text-xl font-semibold text-gray-600 mb-2">Digital Assets Coming Soon!</h3>
                    <p class="text-gray-500">Check back later for downloadable promotional materials.</p>
                </div>
            <?php } ?>
        </div>

        <!-- Participation Submission Section -->
        <div id="participation-submission" class="bg-white rounded-2xl shadow-xl p-6 md:p-8 mb-8 border border-gray-100">
            <div class="flex items-center gap-3 mb-6">
                <div class="w-12 h-12 bg-green-600 rounded-full flex items-center justify-center">
                    <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                    </svg>
                </div>
                <h2 class="text-2xl md:text-3xl font-bold text-gray-900">Participation Submission</h2>
            </div>

            <?php
            if (isset($_REQUEST['promo-submission'])) {
                acf_form_head();

                if (!isset($promotion_submission_post_id)) {
            ?>
                    <div class="bg-blue-50 border border-blue-200 rounded-lg p-6 mb-6">
                        <h3 class="text-xl font-bold text-gray-900 mb-4">Submit Your Proof of Participation</h3>
                        <?php
                        acf_form(array(
                            'post_id'       => 'new_post',
                            'updated_message' => __('<p class="text-green-600 font-semibold">Your submission has been saved successfully!</p>', 'acf'),
                            'post_content' => false,
                            'honeypot' => true,
                            'new_post'      => array(
                                'post_type'     => 'promo-submission',
                                'post_status'   => 'publish'
                            ),
                            'submit_value'  => 'Submit Store Promotion',
                            'html_before_fields' => '<div class="space-y-4">',
                            'html_after_fields' => '</div>',
                        ));
                        ?>
                    </div>
            <?php
                } else {
            ?>
                    <div class="bg-green-50 border border-green-200 rounded-lg p-6 mb-6">
                        <h3 class="text-xl font-bold text-gray-900 mb-4">Update Your Proof of Participation</h3>
                        <?php
                        $acf_form_args = array(
                            'post_id' => $promotion_submission_post_id,
                            'submit_value' => 'Update Your Submission',
                            'html_before_fields' => '<div class="space-y-4">',
                            'html_after_fields' => '</div>',
                        );
                        acf_form($acf_form_args);
                        ?>
                    </div>
            <?php
                }
            } else {
            ?>
                <div class="text-center py-8">
                    <p class="text-gray-700 mb-6">Submit your proof of participation for this promotion.</p>
                    <a href="?promo-submission=<?php echo esc_attr($post_id); ?>" 
                       class="inline-flex items-center gap-2 bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700 text-white px-8 py-4 rounded-lg font-semibold text-lg transition-all shadow-lg hover:shadow-xl">
                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                        </svg>
                        <?php echo $promotion_submission_post_id ? "Update" : "Submit"; ?> Your Proof of Participation
                    </a>
                </div>
            <?php
            }
            ?>
        </div>
    </div>
</div>

<!-- Sign Up Modal -->
<div id="signupModal" class="fixed inset-0 z-50 hidden overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
    <div class="flex items-center justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
        <!-- Background overlay -->
        <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" onclick="closeSignupModal()"></div>

        <!-- Modal panel -->
        <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-2xl sm:w-full">
            <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                <div class="flex items-center justify-between mb-4">
                    <h3 class="text-2xl font-bold text-gray-900" id="modal-title">
                        <?php
                        // Check if user has already signed up
                        $modal_existing_signup_id = null;
                        if (class_exists('\STW\AnchorUp\AnchorUp')) {
                            $anchor_account_number = \STW\AnchorUp\AnchorUp::getAnchorAccountNumber();
                            if ($anchor_account_number) {
                                $signup_query = new WP_Query(array(
                                    'post_type' => 'promo-signup',
                                    'posts_per_page' => 1,
                                    'meta_query' => array(
                                        'relation' => 'AND',
                                        array(
                                            'key' => 'specific_signup_anchor_customer_number',
                                            'value' => $anchor_account_number,
                                            'compare' => '=',
                                        ),
                                        array(
                                            'key' => 'specific_signup_promotion_relationship',
                                            'value' => $post_id,
                                            'compare' => '=',
                                        ),
                                    ),
                                    'fields' => 'ids',
                                ));
                                
                                if ($signup_query->have_posts()) {
                                    $modal_existing_signup_id = $signup_query->posts[0];
                                }
                                wp_reset_postdata();
                            }
                        }
                        echo $modal_existing_signup_id ? 'Update Your Sign-Up' : 'Sign Up for This Promotion';
                        ?>
                    </h3>
                    <button onclick="closeSignupModal()" class="text-gray-400 hover:text-gray-500">
                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>
                <div class="mt-4" id="signupModalContent">
                    <?php
                    // Check if user has already signed up for this promotion
                    $modal_existing_signup_id = null;
                    if (class_exists('\STW\AnchorUp\AnchorUp')) {
                        $anchor_account_number = \STW\AnchorUp\AnchorUp::getAnchorAccountNumber();
                        if ($anchor_account_number) {
                            $signup_query = new WP_Query(array(
                                'post_type' => 'promo-signup',
                                'posts_per_page' => 1,
                                'meta_query' => array(
                                    'relation' => 'AND',
                                    array(
                                        'key' => 'specific_signup_anchor_customer_number',
                                        'value' => $anchor_account_number,
                                        'compare' => '=',
                                    ),
                                    array(
                                        'key' => 'specific_signup_promotion_relationship',
                                        'value' => $post_id,
                                        'compare' => '=',
                                    ),
                                ),
                                'fields' => 'ids',
                            ));
                            
                            if ($signup_query->have_posts()) {
                                $modal_existing_signup_id = $signup_query->posts[0];
                            }
                            wp_reset_postdata();
                        }
                    }
                    
                    if (!$modal_existing_signup_id) {
                        // Get the ACF field key for the promotion relationship field
                        $promotion_field = acf_get_field('specific_signup_promotion_relationship');
                        $promotion_field_key = $promotion_field ? $promotion_field['key'] : '';
                        
                        acf_form(array(
                            'post_id'       => 'new_post',
                            'updated_message' => __('<p class="text-green-600 font-semibold mb-4">Your sign-up has been submitted successfully!</p>', 'acf'),
                            'return'        => get_permalink($post_id),
                            'post_content' => false,
                            'honeypot' => true,
                            'new_post'      => array(
                                'post_type'     => 'promo-signup',
                                'post_status'   => 'publish'
                            ),
                            'submit_value'  => 'Sign Up for Promotion',
                            'html_before_fields' => '<div class="space-y-4">' . ($promotion_field_key ? '<input type="hidden" name="acf[' . esc_attr($promotion_field_key) . ']" value="' . esc_attr($post_id) . '">' : ''),
                            'html_after_fields' => '</div>',
                        ));
                    } else {
                        // Get the ACF field key for the promotion relationship field
                        $promotion_field = acf_get_field('specific_signup_promotion_relationship');
                        $promotion_field_key = $promotion_field ? $promotion_field['key'] : '';
                        
                        $acf_form_args = array(
                            'post_id' => $modal_existing_signup_id,
                            'updated_message' => __('<p class="text-green-600 font-semibold mb-4">Your sign-up has been updated successfully!</p>', 'acf'),
                            'return' => get_permalink($post_id),
                            'submit_value' => 'Update Sign-Up',
                            'html_before_fields' => '<div class="space-y-4">' . ($promotion_field_key ? '<input type="hidden" name="acf[' . esc_attr($promotion_field_key) . ']" value="' . esc_attr($post_id) . '">' : ''),
                            'html_after_fields' => '</div>',
                        );
                        acf_form($acf_form_args);
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .acf-fields .acf-checkbox-list input {
        width: auto;
        margin-top: 5px !important;
    }
    .acf-fields .acf-checkbox-list label {
        font-size: 15px;
        display: inline-flex;
        align-items: start;
        margin-bottom: 20px;
    }
    .prose img {
        border-radius: 0.5rem;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    }
    #participation-submission {
        scroll-margin-top: 100px;
    }
    
    #sign-up-promotion {
        scroll-margin-top: 100px;
    }
    
    /* Hide the promotion relationship field when it's pre-populated */
    .acf-field[data-name="specific_signup_promotion_relationship"].acf-hidden {
        display: none !important;
    }
    
    /* Modal styles */
    #signupModal {
        z-index: 9999;
    }
    
    #signupModal .bg-white {
        max-height: 90vh;
        overflow-y: auto;
    }
    
    /* ACF Button Styling */
    .acf-button,
    .acf-button.button,
    .acf-button.button-primary,
    input.acf-button.button.button-primary,
    input.acf-button.button.button-primary.button-large {
        background-color: #2563eb !important;
        background: linear-gradient(to right, #2563eb, #1d4ed8) !important;
        color: #ffffff !important;
        border: none !important;
        border-radius: 0.5rem !important;
        padding: 0.75rem 1.5rem !important;
        font-weight: 600 !important;
        font-size: 1rem !important;
        cursor: pointer !important;
        transition: all 0.3s ease !important;
        box-shadow: 0 4px 6px -1px rgba(37, 99, 235, 0.3) !important;
        text-decoration: none !important;
        display: inline-block !important;
    }
    
    .acf-button:hover,
    .acf-button.button:hover,
    .acf-button.button-primary:hover,
    input.acf-button.button.button-primary:hover,
    input.acf-button.button.button-primary.button-large:hover {
        background-color: #1d4ed8 !important;
        background: linear-gradient(to right, #1d4ed8, #1e40af) !important;
        box-shadow: 0 6px 12px -2px rgba(37, 99, 235, 0.4) !important;
        transform: translateY(-1px) !important;
    }
    
    .acf-button:active,
    .acf-button.button:active,
    .acf-button.button-primary:active,
    input.acf-button.button.button-primary:active,
    input.acf-button.button.button-primary.button-large:active {
        transform: translateY(0) !important;
        box-shadow: 0 2px 4px -1px rgba(37, 99, 235, 0.3) !important;
    }
    
    /* Large button specific styling */
    .acf-button.button-large,
    input.acf-button.button.button-primary.button-large {
        padding: 1rem 2rem !important;
        font-size: 1.125rem !important;
    }
    
    /* Add Row button specific styling */
    .acf-button[data-event="add-row"] {
        background-color: #10b981 !important;
        background: linear-gradient(to right, #10b981, #059669) !important;
        box-shadow: 0 4px 6px -1px rgba(16, 185, 129, 0.3) !important;
    }
    
    .acf-button[data-event="add-row"]:hover {
        background-color: #059669 !important;
        background: linear-gradient(to right, #059669, #047857) !important;
        box-shadow: 0 6px 12px -2px rgba(16, 185, 129, 0.4) !important;
    }
    
    /* AJAX form submission styles */
    #signupModal form.acf-form .acf-spinner {
        display: none;
        margin-left: 10px;
        vertical-align: middle;
    }
    
    #signupModal form.acf-form.submitting .acf-spinner {
        display: inline-block !important;
    }
    
    #signupModal form.acf-form input[type="submit"]:disabled,
    #signupModal form.acf-form button[type="submit"]:disabled {
        opacity: 0.6;
        cursor: not-allowed;
    }
    
    #signupModal .acf-notice {
        margin: 15px 0;
        padding: 12px 15px;
        border-radius: 6px;
    }
    
    #signupModal .acf-notice.-success {
        background-color: #d1fae5;
        border-left: 4px solid #10b981;
        color: #065f46;
    }
    
    #signupModal .acf-notice.-error {
        background-color: #fee2e2;
        border-left: 4px solid #ef4444;
        color: #991b1b;
    }
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    // Check if promo-submission parameter exists in URL
    const urlParams = new URLSearchParams(window.location.search);
    const promoSubmission = urlParams.get('promo-submission');
    const promoSignup = urlParams.get('promo-signup');
    
    if (promoSubmission) {
        // Wait a bit for the page to fully load, especially if ACF form needs to render
        setTimeout(function() {
            const submissionSection = document.getElementById('participation-submission');
            if (submissionSection) {
                // Smooth scroll to the submission section
                submissionSection.scrollIntoView({ 
                    behavior: 'smooth', 
                    block: 'start' 
                });
                
                // Add a highlight effect
                submissionSection.style.transition = 'box-shadow 0.3s ease';
                submissionSection.style.boxShadow = '0 0 0 4px rgba(34, 197, 94, 0.3)';
                
                // Remove highlight after 3 seconds
                setTimeout(function() {
                    submissionSection.style.boxShadow = '';
                }, 3000);
            }
        }, 500); // Wait 500ms for page to render
    }
    
    if (promoSignup) {
        // Open the modal if promo-signup parameter is in URL
        openSignupModal();
    }
});

// Modal functions
function openSignupModal() {
    const modal = document.getElementById('signupModal');
    if (modal) {
        modal.classList.remove('hidden');
        document.body.style.overflow = 'hidden'; // Prevent background scrolling
        
        // Hide the promotion relationship field
        setTimeout(function() {
            const promotionField = document.querySelector('#signupModal .acf-field[data-name="specific_signup_promotion_relationship"]');
            if (promotionField) {
                promotionField.style.display = 'none';
            }
        }, 100);
    }
}

function closeSignupModal() {
    const modal = document.getElementById('signupModal');
    if (modal) {
        modal.classList.add('hidden');
        document.body.style.overflow = ''; // Restore scrolling
    }
}

            // Close modal on Escape key
            document.addEventListener('keydown', function(e) {
                if (e.key === 'Escape') {
                    closeSignupModal();
                }
            });
            
            // Handle ACF form submission in modal via AJAX
            document.addEventListener('DOMContentLoaded', function() {
                const signupForm = document.querySelector('#signupModal form.acf-form');
                if (signupForm) {
                    signupForm.addEventListener('submit', function(e) {
                        e.preventDefault();
                        e.stopPropagation();
                        
                        const form = this;
                        const submitButton = form.querySelector('input[type="submit"], button[type="submit"]');
                        const originalButtonText = submitButton ? submitButton.value || submitButton.textContent : '';
                        
                        // Add submitting class to form
                        form.classList.add('submitting');
                        
                        // Disable submit button
                        if (submitButton) {
                            submitButton.disabled = true;
                            if (submitButton.value) {
                                submitButton.value = 'Submitting...';
                            } else {
                                submitButton.textContent = 'Submitting...';
                            }
                        }
                        
                        // Show spinner if available
                        const spinner = form.querySelector('.acf-spinner');
                        if (spinner) {
                            spinner.style.display = 'inline-block';
                        }
                        
                        // Remove any existing error/success messages
                        const existingMessages = form.querySelectorAll('.acf-notice');
                        existingMessages.forEach(function(msg) {
                            msg.remove();
                        });
                        
                        // Get form data - ACF forms include all necessary data
                        const formData = new FormData(form);
                        formData.append('action', 'submit_promo_signup');
                        
                        // Submit via AJAX
                        fetch('<?php echo admin_url('admin-ajax.php'); ?>', {
                            method: 'POST',
                            body: formData,
                            credentials: 'same-origin'
                        })
                        .then(function(response) {
                            return response.json();
                        })
                        .then(function(data) {
                            if (data.success) {
                                // Hide the form
                                form.style.display = 'none';
                                
                                // Show success message in modal
                                const modalContent = document.getElementById('signupModalContent');
                                if (modalContent) {
                                    const successMessage = document.createElement('div');
                                    successMessage.className = 'text-center py-8';
                                    successMessage.innerHTML = '<div class="bg-green-50 border border-green-200 rounded-lg p-8 mb-4">' +
                                        '<div class="flex items-center justify-center mb-4">' +
                                        '<svg class="w-16 h-16 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">' +
                                        '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>' +
                                        '</svg>' +
                                        '</div>' +
                                        '<h3 class="text-2xl font-bold text-gray-900 mb-4">Sign-up Submitted Successfully!</h3>' +
                                        '<p class="text-lg text-gray-700">Sign-up submitted successfully! An Anchor team representative will be reaching out to you soon with next steps Thank you!</p>' +
                                        '</div>' +
                                        '<button onclick="closeSignupModal()" class="inline-flex items-center gap-2 bg-gray-600 hover:bg-gray-700 text-white px-6 py-3 rounded-lg font-semibold transition-all">' +
                                        '<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">' +
                                        '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>' +
                                        '</svg>' +
                                        'Close' +
                                        '</button>';
                                    
                                    modalContent.innerHTML = '';
                                    modalContent.appendChild(successMessage);
                                }
                            } else {
                                // Show error message
                                const errorMessage = document.createElement('div');
                                errorMessage.className = 'acf-notice -error acf-message acf-message-error';
                                errorMessage.innerHTML = '<p class="text-red-600 font-semibold mb-4">' + (data.data.message || 'An error occurred. Please try again.') + '</p>';
                                form.insertBefore(errorMessage, form.firstChild);
                                
                                // Remove submitting class
                                form.classList.remove('submitting');
                                
                                // Re-enable submit button
                                if (submitButton) {
                                    submitButton.disabled = false;
                                    if (submitButton.value) {
                                        submitButton.value = originalButtonText;
                                    } else {
                                        submitButton.textContent = originalButtonText;
                                    }
                                }
                                
                                // Hide spinner
                                if (spinner) {
                                    spinner.style.display = 'none';
                                }
                                
                                // Scroll to error
                                errorMessage.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
                            }
                        })
                        .catch(function(error) {
                            console.error('AJAX Error:', error);
                            
                            // Show error message
                            const errorMessage = document.createElement('div');
                            errorMessage.className = 'acf-notice -error acf-message acf-message-error';
                            errorMessage.innerHTML = '<p class="text-red-600 font-semibold mb-4">An error occurred. Please try again.</p>';
                            form.insertBefore(errorMessage, form.firstChild);
                            
                            // Remove submitting class
                            form.classList.remove('submitting');
                            
                            // Re-enable submit button
                            if (submitButton) {
                                submitButton.disabled = false;
                                if (submitButton.value) {
                                    submitButton.value = originalButtonText;
                                } else {
                                    submitButton.textContent = originalButtonText;
                                }
                            }
                            
                            // Hide spinner
                            if (spinner) {
                                spinner.style.display = 'none';
                            }
                        });
                    });
                }
            });
</script>

<?php
get_footer();
?>
