<?php

/**
 * Anchor Up Promotion Hooks
 * WordPress hooks and filters for Anchor Up Promotions
 */

if (!defined('ABSPATH')) {
    exit;
}

// SendGrid Template Mappings
// Fallback template IDs if stw_config is not available
function anchor_up_get_sendgrid_template_id($template_key) {
    $template_mappings = [
        'connection-plus-admin-onboard-form' => 'd-8424a6f04a504ad3bf23fbf413a73339',
        'connection-plus-admin-initial-register-form' => 'd-9a8983f0ef794bfc9a6e6c59b2323b18',
        'anchor-up-foot-traffic-registration' => 'd-829d9a79a4ed441a843f386d95373c04',
        'wordpress-password-reset' => '', // Add your SendGrid template ID here
    ];
    
    // Try stw_config first
    if (function_exists('stw_config')) {
        $template_id = stw_config('sendgrid-template-mapping.' . $template_key);
        if (!empty($template_id)) {
            return $template_id;
        }
    }
    
    // Fallback to direct mapping
    if (isset($template_mappings[$template_key])) {
        return $template_mappings[$template_key];
    }
    
    return '';
}

// Register post types
add_action('init', 'anchor_up_promotion_register_post_types');
function anchor_up_promotion_register_post_types() {
    if (function_exists('register_extended_post_type')) {
        register_extended_post_type('promo-submission', [
            'supports' => ['title', 'custom-fields'],
            'menu_icon' => 'dashicons-megaphone'
        ]);
        register_extended_post_type('anchor-up-promotion', [
            'supports' => ['title', 'custom-fields', 'thumbnail', 'editor'],
            'menu_icon' => 'dashicons-megaphone'
        ]);
    } else {
        // Fallback to standard WordPress register_post_type
        register_post_type('promo-submission', [
            'public' => true,
            'supports' => ['title', 'custom-fields'],
            'menu_icon' => 'dashicons-megaphone'
        ]);
        register_post_type('anchor-up-promotion', [
            'public' => true,
            'supports' => ['title', 'custom-fields', 'thumbnail', 'editor'],
            'menu_icon' => 'dashicons-megaphone'
        ]);
    }
}

// Change post type link domain (only if Store() function exists)
add_filter('post_type_link', 'anchor_up_promotion_change_post_type_link_domain', 10, 2);
function anchor_up_promotion_change_post_type_link_domain($permalink, $post) {
    if ('anchor-up-promotion' === $post->post_type && is_admin()) {
        // Only use Store() if the function exists
        if (function_exists('Store')) {
            $store = Store();
            if (method_exists($store, 'getDomainFromStoreId')) {
                $permalink = str_replace(get_site_url(), $store->getDomainFromStoreId('anchor-up', true), $permalink);
            }
        }
    }
    return $permalink;
}

// Auto Link Store Promo Submission to Anchor Up Store
add_filter('acf/load_field/name=_post_title', 'anchor_up_promotion_load_post_title_field', 10, 3);
function anchor_up_promotion_load_post_title_field($field) {
    $title = "Test";
    $field['value'] = $title;
    return $field;
}

// Auto Link Store Promo Submission to Anchor Up Promotion
add_filter('acf/load_field/name=anchor_up_promotion_relationship', 'anchor_up_promotion_load_promotion_relationship_field', 10, 3);
function anchor_up_promotion_load_promotion_relationship_field($field) {
    if (!is_admin()) {
        $current_promotion_post = get_post();
        if (isset($current_promotion_post)) {
            $field['instructions'] = '';
            $field['value'] = $current_promotion_post;
        }
    }
    return $field;
}

// Auto Link Store Promo Submission to Anchor Account Number
add_filter('acf/load_field/name=anchor_account_number', 'anchor_up_promotion_load_account_number_field', 10, 3);
function anchor_up_promotion_load_account_number_field($field) {
    if (!is_admin()) {
        if (class_exists('\STW\AnchorUp\AnchorUp')) {
            $store = \STW\AnchorUp\AnchorUp::isAnchorUpAdmin(true);
            $anchor_account_number = \STW\AnchorUp\AnchorUp::getAnchorAccountNumber($store);
            if (isset($anchor_account_number)) {
                $field['value'] = $anchor_account_number;
            }
        }
    }
    return $field;
}

// Auto Link Store Promo Submission to Anchor Autogenerated Store Id from Airtables
add_filter('acf/load_field/name=autogenerated_store_id', 'anchor_up_promotion_load_autogenerated_store_id_field', 10, 3);
function anchor_up_promotion_load_autogenerated_store_id_field($field) {
    if (!is_admin()) {
        if (class_exists('\STW\AnchorUp\AnchorUp')) {
            $store = \STW\AnchorUp\AnchorUp::isAnchorUpAdmin(true);
            $autogenerated_store_id = \STW\AnchorUp\AnchorUp::getAnchorUpAutoGeneratedStoreId($store);
            if (isset($autogenerated_store_id)) {
                $field['value'] = $autogenerated_store_id;
            }
        }
    }
    return $field;
}

// Auto-populate Store ID field
add_filter('acf/load_field/name=store_id', 'anchor_up_promotion_load_store_id_field', 10, 3);
function anchor_up_promotion_load_store_id_field($field) {
    if (!is_admin()) {
        if (class_exists('\STW\AnchorUp\AnchorUp')) {
            $store = \STW\AnchorUp\AnchorUp::isAnchorUpAdmin(true);
            if ($store && isset($store->autonumber)) {
                $field['value'] = $store->autonumber;
            }
        } elseif (function_exists('Store')) {
            $store = Store();
            if ($store && method_exists($store, 'autonumber')) {
                $field['value'] = $store->autonumber;
            } elseif ($store && isset($store->autonumber)) {
                $field['value'] = $store->autonumber;
            }
        }
    }
    return $field;
}

// Auto-populate Store Name field
add_filter('acf/load_field/name=store_name', 'anchor_up_promotion_load_store_name_field', 10, 3);
function anchor_up_promotion_load_store_name_field($field) {
    if (!is_admin()) {
        if (class_exists('\STW\AnchorUp\AnchorUp')) {
            $store = \STW\AnchorUp\AnchorUp::isAnchorUpAdmin(true);
            if ($store && isset($store->name)) {
                $field['value'] = $store->name;
            }
        } elseif (function_exists('Store')) {
            $store = Store();
            if ($store && method_exists($store, 'name')) {
                $field['value'] = $store->name;
            } elseif ($store && isset($store->name)) {
                $field['value'] = $store->name;
            }
        }
    }
    return $field;
}

// Update post title on ACF save and save Store ID/Name
add_action('acf/save_post', 'anchor_up_promotion_update_post_title_on_save', 20);
function anchor_up_promotion_update_post_title_on_save($post_id) {
    if (isset($_POST['acf'])) {
        $post_type = get_post_type($post_id);
        if ($post_type == "promo-submission") {
            $store_id = '';
            $store_name = '';
            
            // Get Store ID and Name from form or store object
            // ACF uses field keys in $_POST['acf']
            if (isset($_POST['acf']['field_store_id_promo'])) {
                $store_id = sanitize_text_field($_POST['acf']['field_store_id_promo']);
            }
            if (isset($_POST['acf']['field_store_name_promo'])) {
                $store_name = sanitize_text_field($_POST['acf']['field_store_name_promo']);
            }
            
            // If not in form, try to get from store object
            if (empty($store_id) || empty($store_name)) {
                if (class_exists('\STW\AnchorUp\AnchorUp')) {
                    $store = \STW\AnchorUp\AnchorUp::isAnchorUpAdmin(true);
                    if ($store) {
                        if (empty($store_id) && isset($store->autonumber)) {
                            $store_id = $store->autonumber;
                        }
                        if (empty($store_name) && isset($store->name)) {
                            $store_name = $store->name;
                        }
                    }
                } elseif (function_exists('Store')) {
                    $store = Store();
                    if ($store) {
                        if (empty($store_id)) {
                            $store_id = method_exists($store, 'autonumber') ? $store->autonumber : (isset($store->autonumber) ? $store->autonumber : '');
                        }
                        if (empty($store_name)) {
                            $store_name = method_exists($store, 'name') ? $store->name : (isset($store->name) ? $store->name : '');
                        }
                    }
                }
            }
            
            // Save Store ID and Store Name to post meta
            if (!empty($store_id)) {
                update_post_meta($post_id, 'store_id', $store_id);
                // Also update ACF field if it exists
                update_field('store_id', $store_id, $post_id);
            }
            if (!empty($store_name)) {
                update_post_meta($post_id, 'store_name', $store_name);
                // Also update ACF field if it exists
                update_field('store_name', $store_name, $post_id);
            }
            
            // Update post title
            if (class_exists('\STW\AnchorUp\AnchorUp')) {
                $store = \STW\AnchorUp\AnchorUp::isAnchorUpAdmin(true);

                $promo_id = isset($_POST['acf']['field_64381a6072103']) ? $_POST['acf']['field_64381a6072103'] : null;

                if ($promo_id) {
                    $promo_post = get_post($promo_id);
                    if ($promo_post) {
                        $promo_post_title = $promo_post->post_title;
                        $post_title = ($store_name ?: ($store ? $store->name : '')) . ' - Acct #: ' . ($store ? $store->anchor_customer_id : '') . ' - Store Id: ' . ($store_id ?: ($store ? $store->autonumber : '')) . ' - Promo: ' . $promo_post_title;

                        $post_data = array(
                            'ID' => $post_id,
                            'post_title' => $post_title,
                        );

                        wp_update_post($post_data);
                    }
                }
            }
        }
    }
}

// Custom validation rule to check for overlapping date ranges
add_filter('acf/validate_value/name=promotion_start_date', 'anchor_up_promotion_validate_start_date', 10, 4);
function anchor_up_promotion_validate_start_date($valid, $value, $field, $input) {
    $post_id = isset($_POST['post_ID']) ? $_POST['post_ID'] : 0;
    $meta_key_start = 'promotion_start_date';
    $meta_key_end = 'promotion_end_date';

    $start_date = strtotime(get_field($meta_key_start, $post_id));
    $end_date = strtotime(get_field($meta_key_end, $post_id));

    if ($start_date && $end_date && $start_date >= $end_date) {
        $valid = 'Start date must be before end date.';
    }

    // Check for overlapping date ranges
    $query = new WP_Query(array(
        'post_type' => 'anchor-up-promotion',
        'post__not_in' => array($post_id),
        'meta_query' => array(
            'relation' => 'AND',
            array(
                'key' => $meta_key_start,
                'value' => $value,
                'compare' => '<=',
                'type' => 'DATE',
            ),
            array(
                'key' => $meta_key_end,
                'value' => $value,
                'compare' => '>=',
                'type' => 'DATE',
            ),
        ),
    ));

    if ($query->have_posts()) {
        $overlapping_posts = array();
        while ($query->have_posts()) {
            $query->the_post();
            $post_title = get_the_title();
            $post_id_overlap = get_the_ID();
            $edit_link = get_edit_post_link($post_id_overlap);
            $overlapping_posts[] = "<a href='$edit_link' target='_blank'>$post_title</a>";
        }
        wp_reset_query();

        $overlapping_posts_html = implode(', ', $overlapping_posts);
        $valid = "Date range overlaps with the following existing entries: $overlapping_posts_html";
    }

    return $valid;
}

// Add custom columns to Anchor Up Promotion admin list
add_filter('manage_anchor-up-promotion_posts_columns', 'anchor_up_promotion_add_admin_columns');
function anchor_up_promotion_add_admin_columns($columns) {
    // Insert Promotion Start Date after title
    $new_columns = array();
    foreach ($columns as $key => $value) {
        $new_columns[$key] = $value;
        if ($key === 'title') {
            $new_columns['promotion_start_date'] = 'Promotion Start Date';
            $new_columns['promotion_end_date'] = 'Promotion End Date';
        }
    }
    return $new_columns;
}

// Populate custom column content
add_action('manage_anchor-up-promotion_posts_custom_column', 'anchor_up_promotion_populate_admin_columns', 10, 2);
function anchor_up_promotion_populate_admin_columns($column, $post_id) {
    switch ($column) {
        case 'promotion_start_date':
            $start_date = get_field('promotion_start_date', $post_id);
            if ($start_date) {
                // Format the date nicely
                $date_timestamp = strtotime($start_date);
                $today = strtotime(date('Ymd'));
                
                echo '<strong>' . esc_html($start_date) . '</strong>';
                
                // Add status indicator
                $end_date = get_field('promotion_end_date', $post_id);
                if ($end_date) {
                    $end_timestamp = strtotime($end_date);
                    if ($today >= $date_timestamp && $today <= $end_timestamp) {
                        echo '<br><span style="color: #10b981; font-size: 11px;">● Active Now</span>';
                    } elseif ($today < $date_timestamp) {
                        $days_until = ceil(($date_timestamp - $today) / 86400);
                        echo '<br><span style="color: #f59e0b; font-size: 11px;">● Starts in ' . $days_until . ' day' . ($days_until != 1 ? 's' : '') . '</span>';
                    } elseif ($today > $end_timestamp) {
                        echo '<br><span style="color: #6b7280; font-size: 11px;">● Ended</span>';
                    }
                }
            } else {
                echo '<span style="color: #9ca3af;">—</span>';
            }
            break;
            
        case 'promotion_end_date':
            $end_date = get_field('promotion_end_date', $post_id);
            if ($end_date) {
                echo esc_html($end_date);
            } else {
                echo '<span style="color: #9ca3af;">—</span>';
            }
            break;
    }
}

// Make columns sortable
add_filter('manage_edit-anchor-up-promotion_sortable_columns', 'anchor_up_promotion_make_columns_sortable');
function anchor_up_promotion_make_columns_sortable($columns) {
    $columns['promotion_start_date'] = 'promotion_start_date';
    $columns['promotion_end_date'] = 'promotion_end_date';
    return $columns;
}

// Handle the sorting
add_action('pre_get_posts', 'anchor_up_promotion_handle_admin_sorting');
function anchor_up_promotion_handle_admin_sorting($query) {
    // Only run in admin and for our post type
    if (!is_admin() || !$query->is_main_query()) {
        return;
    }
    
    if ($query->get('post_type') !== 'anchor-up-promotion') {
        return;
    }
    
    // Get the orderby value
    $orderby = $query->get('orderby');
    
    // Set default sorting to promotion_start_date ASC (most upcoming first)
    if (empty($orderby) || $orderby === 'date') {
        $query->set('meta_key', 'promotion_start_date');
        $query->set('orderby', 'meta_value');
        $query->set('order', 'ASC');
    }
    
    // Handle custom column sorting
    if ($orderby === 'promotion_start_date' || $orderby === 'promotion_end_date') {
        $query->set('meta_key', $orderby);
        $query->set('orderby', 'meta_value');
        
        // Get the order (default to ASC for start date, DESC for end date)
        $order = $query->get('order');
        if (empty($order)) {
            $order = ($orderby === 'promotion_start_date') ? 'ASC' : 'DESC';
            $query->set('order', $order);
        }
    }
}

// Anchor Up Register Form
add_action('init', 'anchor_up_promotion_setup_register_form_hook');
function anchor_up_promotion_setup_register_form_hook() {
    // Check if Gravity Forms is active
    if (!class_exists('RGFormsModel')) {
        return;
    }
    
    $anchor_up_register_form_id = RGFormsModel::get_form_id("Anchor Up - Register");
    
    if (!$anchor_up_register_form_id) {
        return;
    }
    
    $anchor_up_register_form = 'gform_after_submission_' . $anchor_up_register_form_id;
    
    add_action($anchor_up_register_form, 'anchor_up_promotion_handle_register_form_submission', 10, 2);
}

function anchor_up_promotion_handle_register_form_submission($entry, $form) {
    $user_email = strtolower(rgar($entry, '39'));
    $form_id = rgar($entry, 'form_id');
    $form_date_submitted = rgar($entry, 'date_created');
    $entry_id = rgar($entry, 'id');
    $source_url = rgar($entry, 'source_url');
    $program = rgar($entry, '26');
    
    $pos = rgar($entry, '28');
    $other_pos = rgar($entry, '29');
    
    if ($other_pos) {
        $pos = $other_pos;
    }
    
    $current_user = wp_get_current_user();
    $first_name = $current_user->user_firstname;
    $last_name = $current_user->user_lastname;
    
    $new_store_onboard = array(
        'Name' => rgar($entry, '4'),
        'URL' => rgar($entry, '27'),
        'first_name' => $first_name,
        'last_name' => $last_name,
        'email' => $user_email,
        'anchor_customer_id' => rgar($entry, '3'),
        'pos_system' => $pos,
        'bookstore_type' => rgar($entry, '20'),
        'program_interested' => $program,
        'Status' => 'Pending Approval',
        'Notes' => rgar($entry, '30'),
        'has_social_media' => rgar($entry, '32'),
        'uses_social_media_agency' => rgar($entry, '33'),
        'interested_in_him_first_media' => rgar($entry, '34'),
        'questions' => rgar($entry, '35'),
        'current_website_url' => rgar($entry, '27'),
        'facebook_url' => rgar($entry, '37'),
        'instagram_username' => rgar($entry, '38'),
        'street_address' => rgar($entry, '36.1') . ' ' . rgar($entry, '36.2'),
        'city' => rgar($entry, '36.3'),
        'state' => rgar($entry, '36.4'),
        'zipcode' => rgar($entry, '36.5'),
        'marketing_group' => rgar($entry, '44'),
        'anchor_ship_to_id' => rgar($entry, '47'),
        'street_address' => rgar($entry, '45.1'),
        'city' => rgar($entry, '45.3'),
        'state' => rgar($entry, '45.4'),
        'zipcode' => rgar($entry, '45.5'),
        'country' => rgar($entry, '45.6')
    );
    
    // Save to Airtable - Tab: Connection Plus
    if (function_exists('anchor_up_airtable_post_data')) {
        $post = anchor_up_airtable_post_data($new_store_onboard, 'anchor_up_foot_traffic_stores');
    } elseif (class_exists('STW\Airtable\Airtable')) {
        $post = \STW\Airtable\Airtable::postData($new_store_onboard, 'anchor_up_foot_traffic_stores');
    }
    
    // Create in Customer.io
    $form_details = [
        'form-id' => $form_id,
        'form-title' => 'anchor-up-register',
        'store_name' => rgar($entry, '4'),
        'site_url' => rgar($entry, '27'),
        'anchor_customer_id' => rgar($entry, '3'),
        'pos_system' => $pos,
        'bookstore_type' => rgar($entry, '20'),
        'program_interested' => $program,
        'has_social_media' => rgar($entry, '32'),
        'uses_social_media_agency' => rgar($entry, '33'),
        'interested_in_him_first_media' => rgar($entry, '34'),
        'questions' => rgar($entry, '35'),
    ];
    
    // Send email via Sendgrid if available
    $template_id = anchor_up_get_sendgrid_template_id('anchor-up-foot-traffic-registration');
    
    $sendgrid_response_data = null;
    if ($template_id) {
        if (function_exists('Store') && function_exists('anchor_up_sendgrid_send_email')) {
            $store_data = Store();
            if ($store_data && method_exists($store_data, 'send_as_email')) {
                $res = anchor_up_sendgrid_send_email(
                    $store_data->send_as_email, 
                    $store_data->name, 
                    $user_email, 
                    $template_id, 
                    $form_details
                );
                
                // Store response for JavaScript output
                if ($res) {
                    try {
                        $status_code = method_exists($res, 'statusCode') ? $res->statusCode() : null;
                        $response_body = method_exists($res, 'body') ? $res->body() : null;
                        $sendgrid_response_data = [
                            'status_code' => $status_code,
                            'body' => $response_body,
                            'from' => $store_data->send_as_email,
                            'to' => $user_email,
                            'template_id' => $template_id
                        ];
                    } catch (\Exception $e) {
                        $sendgrid_response_data = ['error' => $e->getMessage()];
                    }
                }
            }
        } elseif (class_exists('STW\Email\SendGrid')) {
            $store_data = Store();
            if ($store_data && method_exists($store_data, 'send_as_email')) {
                $res = \STW\Email\SendGrid::sendEmail(
                    $store_data->send_as_email, 
                    $store_data->name, 
                    $user_email, 
                    $template_id, 
                    $form_details
                );
                
                // Store response for JavaScript output
                if ($res) {
                    try {
                        $status_code = method_exists($res, 'statusCode') ? $res->statusCode() : null;
                        $response_body = method_exists($res, 'body') ? $res->body() : null;
                        $sendgrid_response_data = [
                            'status_code' => $status_code,
                            'body' => $response_body,
                            'from' => $store_data->send_as_email,
                            'to' => $user_email,
                            'template_id' => $template_id
                        ];
                    } catch (\Exception $e) {
                        $sendgrid_response_data = ['error' => $e->getMessage()];
                    }
                }
            }
        }
    }
    
    // Store SendGrid response and output to console
    if ($sendgrid_response_data) {
        gform_update_meta($entry_id, 'sendgrid_response', json_encode($sendgrid_response_data));
        
        // Add JavaScript to output console log via Gravity Forms confirmation filter
        add_filter('gform_confirmation_' . $form_id, function($confirmation, $form, $entry) use ($sendgrid_response_data) {
            $js_data = json_encode($sendgrid_response_data);
            $script = '<script>
                console.log("SendGrid Email Response:", ' . $js_data . ');
                // Also listen for AJAX confirmations
                if (typeof jQuery !== "undefined") {
                    jQuery(document).on("gform_confirmation_loaded", function(event, formId) {
                        if (formId == ' . $form['id'] . ') {
                            console.log("SendGrid Email Response:", ' . $js_data . ');
                        }
                    });
                }
            </script>';
            return $confirmation . $script;
        }, 10, 3);
    }
    
    // Build HTML email content
    $html = '<h1>New Anchor Up Foot Traffic Registration</h1>';
    $html .= '<h2>View This New Entry in Airtables</h2>';
    $html .= '<p>A new store has registered for Anchor Up. Please check the Anchor Up Dashboard for more details.</p>';
    $html .= '<p>Store Name: ' . esc_html(rgar($entry, '4')) . '</p>';
    $html .= '<p>Store URL: ' . esc_html(rgar($entry, '27')) . '</p>';
    $html .= '<p>Anchor Customer ID: ' . esc_html(rgar($entry, '3')) . '</p>';
    $html .= '<p>POS System: ' . esc_html($pos) . '</p>';
    $html .= '<p>Bookstore Type: ' . esc_html(rgar($entry, '20')) . '</p>';
    $html .= '<p>Program Interested: ' . esc_html($program) . '</p>';
    $html .= '<p>Has Social Media: ' . esc_html(rgar($entry, '32')) . '</p>';
    $html .= '<p>Uses Social Media Agency: ' . esc_html(rgar($entry, '33')) . '</p>';
    $html .= '<p>Interested in Him First Media: ' . esc_html(rgar($entry, '34')) . '</p>';
    $html .= '<p>Current Website URL: ' . esc_html(rgar($entry, '27')) . '</p>';
    $html .= '<p>Facebook URL: ' . esc_html(rgar($entry, '37')) . '</p>';
    $html .= '<p>Instagram Username: ' . esc_html(rgar($entry, '38')) . '</p>';
    $html .= '<p>Street Address: ' . esc_html(rgar($entry, '36.1') . ' ' . rgar($entry, '36.2')) . '</p>';
    $html .= '<p>City: ' . esc_html(rgar($entry, '36.3')) . '</p>';
    $html .= '<p>State: ' . esc_html(rgar($entry, '36.4')) . '</p>';
    $html .= '<p>Zipcode: ' . esc_html(rgar($entry, '36.5')) . '</p>';
    $html .= '<p>Marketing Group: ' . esc_html(rgar($entry, '44')) . '</p>';
    $html .= '<p>anchor_ship_to_id: ' . esc_html(rgar($entry, '47')) . '</p>';
    $html .= '<p>street_address: ' . esc_html(rgar($entry, '45.1')) . '</p>';
    $html .= '<p>city: ' . esc_html(rgar($entry, '45.3')) . '</p>';
    $html .= '<p>state: ' . esc_html(rgar($entry, '45.4')) . '</p>';
    $html .= '<p>zipcode: ' . esc_html(rgar($entry, '45.5')) . '</p>';
    $html .= '<p>country: ' . esc_html(rgar($entry, '45.6')) . '</p>';
    $html .= '<p>Questions: ' . esc_html(rgar($entry, '35')) . '</p>';
    
    $admin_emails = [
        'anchorup@anchordistributors.com',
        'scott.whitaker@anchordistributors.com',
        'customercare@anchordistributors.com'
    ];
    
    // Set email content type to HTML
    add_filter('wp_mail_content_type', function ($content_type) {
        return 'text/html';
    });
    
    // Send emails to admin addresses
    foreach ($admin_emails as $email) {
        wp_mail($email, 'Anchor Up Registration - ' . esc_html(rgar($entry, '4')), $html);
    }
    
    // Remove the content type filter after sending
    remove_filter('wp_mail_content_type', function ($content_type) {
        return 'text/html';
    });
    
    // Clear Airtable cache
    delete_option('_transient_stw.airtable.anchor_up_foot_traffic_stores');
}

// Anchor Up - Official Onboarding Form
add_action('init', 'anchor_up_promotion_setup_website_onboarding_form_hook');
function anchor_up_promotion_setup_website_onboarding_form_hook() {
    // Check if Gravity Forms is active
    if (!class_exists('RGFormsModel')) {
        return;
    }
    
    $on_boarding_form_id = RGFormsModel::get_form_id("Anchor Up - Official Onboarding");
    
    if (!$on_boarding_form_id) {
        return;
    }
    
    $on_boarding_form = 'gform_after_submission_' . $on_boarding_form_id;
    
    add_action($on_boarding_form, 'anchor_up_promotion_handle_website_onboarding_form_submission', 10, 2);
}

// Helper function for dd() (dump and die) - Laravel-style debugging
if (!function_exists('dd')) {
    function dd(...$vars) {
        foreach ($vars as $var) {
            echo '<pre style="background: #f4f4f4; padding: 20px; margin: 20px; border: 2px solid #333; border-radius: 5px; overflow: auto; max-width: 90%;">';
            var_dump($var);
            echo '</pre>';
        }
        die();
    }
}

function anchor_up_promotion_handle_website_onboarding_form_submission($entry, $form) {
    $user_email = strtolower(rgar($entry, '2'));
    $form_id = rgar($entry, 'form_id');
    $form_date_submitted = rgar($entry, 'date_created');
    $entry_id = rgar($entry, 'id');
    $source_url = rgar($entry, 'source_url');
    
    $programs = array(
        rgar($entry, '17.1'),
        rgar($entry, '17.2')
    );
    $programs = implode(', ', array_filter($programs));
    
    $admin_email = rgar($entry, '19');
    
    $new_store_onboard = array(
        'Name' => rgar($entry, '4'),
        'URL' => rgar($entry, '1'),
        'site_type' => 'Bookstore',
        'anchor_customer_id' => rgar($entry, '3'),
        'Store_Association' => rgar($entry, '5'),
        'pos_system' => rgar($entry, '42'),
        'pos_notes' => rgar($entry, '43'),
        'Account_First_Name' => rgar($entry, '6'),
        'Account_Last_Name' => rgar($entry, '7'),
        'Store_In_Store_Phone_Number' => rgar($entry, '9'),
        'Store_Street_Address' => rgar($entry, '18.1'),
        'Store_Street_Address_2' => rgar($entry, '18.2'),
        'Store_City' => rgar($entry, '18.3'),
        'Store_State' => rgar($entry, '18.4'),
        'Store_Zipcode' => rgar($entry, '18.5'),
        'Admin_Email' => rgar($entry, '19'),
        'Send_As_Email' => $admin_email,
        'Support_Email' => rgar($entry, '21'),
        'Webmaster - Contact for DNS' => rgar($entry, '22'),
        // Added a Hashtag, cause the new color plugin doesnt add it.
        'Primary_Theme_Color' => "#" . rgar($entry, '40'),
        'Accent_Theme_Color' => "#" . rgar($entry, '41'),
        'Logo_url' => rgar($entry, '25'),
        'Paperwork_Logo_url' => rgar($entry, '26'),
        'Address_Label_Logo_url' => rgar($entry, '27'),
        'Store_Hours' => rgar($entry, '28'),
        'store_about_us_description' => rgar($entry, '31'),
        'store_exterior_image_url' => rgar($entry, '29'),
        'store_interior_image_url' => rgar($entry, '30'),
        'store_short_intro' => rgar($entry, '32'),
        'store_tagline' => rgar($entry, '34'),
        'In_Store_Services' => rgar($entry, '33'),
        'store_facebook_url' => rgar($entry, '35'),
        'store_instagram_username' => rgar($entry, '36'),
        'store_twitter_username' => rgar($entry, '37'),
        'store_covid_notice' => rgar($entry, '38'),
        'store_additional_information' => rgar($entry, '39')
    );
    
    // Save to Airtable - Tab: Connection Plus
    if (function_exists('anchor_up_airtable_post_data')) {
        $post = anchor_up_airtable_post_data($new_store_onboard, 'connection_plus');
    } elseif (class_exists('STW\Airtable\Airtable')) {
        $post = \STW\Airtable\Airtable::postData($new_store_onboard, 'connection_plus');
    }
    
    $form_details = [
        'form-id' => $form_id,
        'form-title' => 'connection-plus-onboarding',
        'entry-id' => $entry_id,
        'form-date-submitted' => $form_date_submitted,
        'message' => rgar($entry, '3'),
        'source-url' => $source_url,
        'URL' => rgar($entry, '1'),
        'anchor_customer_id' => rgar($entry, '3'),
        'bookstore_name' => rgar($entry, '4'),
        'bookstore association' => rgar($entry, '5'),
        'account_first_name' => rgar($entry, '6'),
        'account_last_name' => rgar($entry, '7'),
        'account_email_address' => rgar($entry, '8'),
        'store_phone_number' => rgar($entry, '9'),
        'store_address_1' => rgar($entry, '18.1'),
        'store_address_2' => rgar($entry, '18.2'),
        'store_city' => rgar($entry, '18.3'),
        'store_state' => rgar($entry, '18.4'),
        'store_zipcode' => rgar($entry, '18.5')
    ];
    
    // Send email via Sendgrid if available
    $template_id = anchor_up_get_sendgrid_template_id('connection-plus-admin-onboard-form');
    
    $sendgrid_response_data = null;
    if ($template_id) {
        if (function_exists('Store') && function_exists('anchor_up_sendgrid_send_email')) {
            $store_data = Store();
            if ($store_data && method_exists($store_data, 'send_as_email')) {
                $res = anchor_up_sendgrid_send_email(
                    $store_data->send_as_email, 
                    $store_data->name, 
                    $admin_email, 
                    $template_id, 
                    $form_details
                );
                
                // Store response for JavaScript output
                if ($res) {
                    try {
                        $status_code = method_exists($res, 'statusCode') ? $res->statusCode() : null;
                        $response_body = method_exists($res, 'body') ? $res->body() : null;
                        $sendgrid_response_data = [
                            'status_code' => $status_code,
                            'body' => $response_body,
                            'from' => $store_data->send_as_email,
                            'to' => $admin_email,
                            'template_id' => $template_id
                        ];
                    } catch (\Exception $e) {
                        $sendgrid_response_data = ['error' => $e->getMessage()];
                    }
                }
            }
        } elseif (class_exists('STW\Email\SendGrid')) {
            $store_data = Store();
            if ($store_data && method_exists($store_data, 'send_as_email')) {
                $res = \STW\Email\SendGrid::sendEmail(
                    $store_data->send_as_email, 
                    $store_data->name, 
                    $admin_email, 
                    $template_id, 
                    $form_details
                );
                
                // Store response for JavaScript output
                if ($res) {
                    try {
                        $status_code = method_exists($res, 'statusCode') ? $res->statusCode() : null;
                        $response_body = method_exists($res, 'body') ? $res->body() : null;
                        $sendgrid_response_data = [
                            'status_code' => $status_code,
                            'body' => $response_body,
                            'from' => $store_data->send_as_email,
                            'to' => $admin_email,
                            'template_id' => $template_id
                        ];
                    } catch (\Exception $e) {
                        $sendgrid_response_data = ['error' => $e->getMessage()];
                    }
                }
            }
        }
    }
    
    // Store SendGrid response and output to console
    if ($sendgrid_response_data) {
        gform_update_meta($entry_id, 'sendgrid_response', json_encode($sendgrid_response_data));
        
        // Add JavaScript to output console log via Gravity Forms confirmation filter
        add_filter('gform_confirmation_' . $form_id, function($confirmation, $form, $entry) use ($sendgrid_response_data) {
            $js_data = json_encode($sendgrid_response_data);
            $script = '<script>
                console.log("SendGrid Email Response:", ' . $js_data . ');
                // Also listen for AJAX confirmations
                if (typeof jQuery !== "undefined") {
                    jQuery(document).on("gform_confirmation_loaded", function(event, formId) {
                        if (formId == ' . $form['id'] . ') {
                            console.log("SendGrid Email Response:", ' . $js_data . ');
                        }
                    });
                }
            </script>';
            return $confirmation . $script;
        }, 10, 3);
    }
    
    // Build HTML email content
    $html = '<h1>New Anchor Up Website Onboarding</h1>';
    $html .= '<h2>View This New Entry in Airtables</h2>';
    $html .= '<p>A new store has onboarded for Connection Plus. Please check the Connection Plus Dashboard for more details.</p>';
    $html .= '<p>Store Name: ' . esc_html(rgar($entry, '4')) . '</p>';
    $html .= '<p>Store URL: ' . esc_html(rgar($entry, '1')) . '</p>';
    $html .= '<p>Anchor Customer ID: ' . esc_html(rgar($entry, '3')) . '</p>';
    $html .= '<p>Store Association: ' . esc_html(rgar($entry, '5')) . '</p>';
    $html .= '<p>POS System: ' . esc_html(rgar($entry, '42')) . '</p>';
    $html .= '<p>POS Notes: ' . esc_html(rgar($entry, '43')) . '</p>';
    $html .= '<p>Account First Name: ' . esc_html(rgar($entry, '6')) . '</p>';
    $html .= '<p>Account Last Name: ' . esc_html(rgar($entry, '7')) . '</p>';
    $html .= '<p>Store In Store Phone Number: ' . esc_html(rgar($entry, '9')) . '</p>';
    $html .= '<p>Store Street Address: ' . esc_html(rgar($entry, '18.1')) . '</p>';
    $html .= '<p>Store Street Address 2: ' . esc_html(rgar($entry, '18.2')) . '</p>';
    $html .= '<p>Store City: ' . esc_html(rgar($entry, '18.3')) . '</p>';
    $html .= '<p>Store State: ' . esc_html(rgar($entry, '18.4')) . '</p>';
    $html .= '<p>Store Zipcode: ' . esc_html(rgar($entry, '18.5')) . '</p>';
    $html .= '<p>Admin Email: ' . esc_html(rgar($entry, '19')) . '</p>';
    $html .= '<p>Support Email: ' . esc_html(rgar($entry, '21')) . '</p>';
    $html .= '<p>Webmaster - Contact for DNS: ' . esc_html(rgar($entry, '22')) . '</p>';
    $html .= '<p>Primary Theme Color: ' . esc_html(rgar($entry, '40')) . '</p>';
    $html .= '<p>Accent Theme Color: ' . esc_html(rgar($entry, '41')) . '</p>';
    $html .= '<p>Logo URL: ' . esc_html(rgar($entry, '25')) . '</p>';
    $html .= '<p>Paperwork Logo URL: ' . esc_html(rgar($entry, '26')) . '</p>';
    $html .= '<p>Address Label Logo URL: ' . esc_html(rgar($entry, '27')) . '</p>';
    $html .= '<p>Store Hours: ' . esc_html(rgar($entry, '28')) . '</p>';
    $html .= '<p>Store About Us Description: ' . esc_html(rgar($entry, '31')) . '</p>';
    $html .= '<p>Store Exterior Image URL: ' . esc_html(rgar($entry, '29')) . '</p>';
    $html .= '<p>Store Interior Image URL: ' . esc_html(rgar($entry, '30')) . '</p>';
    $html .= '<p>Store Short Intro: ' . esc_html(rgar($entry, '32')) . '</p>';
    $html .= '<p>Store Tagline: ' . esc_html(rgar($entry, '34')) . '</p>';
    $html .= '<p>In Store Services: ' . esc_html(rgar($entry, '33')) . '</p>';
    $html .= '<p>Store Facebook URL: ' . esc_html(rgar($entry, '35')) . '</p>';
    $html .= '<p>Store Instagram Username: ' . esc_html(rgar($entry, '36')) . '</p>';
    $html .= '<p>Store Twitter Username: ' . esc_html(rgar($entry, '37')) . '</p>';
    $html .= '<p>Store Covid Notice: ' . esc_html(rgar($entry, '38')) . '</p>';
    $html .= '<p>Store Additional Information: ' . esc_html(rgar($entry, '39')) . '</p>';
    
    $admin_emails = [
        'anchorup@anchordistributors.com',
        'scott.whitaker@anchordistributors.com',
        'customercare@anchordistributors.com'
    ];
    
    // Set email content type to HTML
    add_filter('wp_mail_content_type', function ($content_type) {
        return 'text/html';
    });
    
    // Send emails to admin addresses
    foreach ($admin_emails as $email) {
        wp_mail($email, 'Anchor Up Website - Onboarding - ' . esc_html(rgar($entry, '4')), $html);
    }
    
    // Remove the content type filter after sending
    remove_filter('wp_mail_content_type', function ($content_type) {
        return 'text/html';
    });
    
    // Clear Airtable cache if needed
    delete_option('_transient_stw.airtable.connection_plus');
}

// Auto-create registration pages and assign templates
add_action('admin_init', 'anchor_up_promotion_auto_create_registration_pages');
function anchor_up_promotion_auto_create_registration_pages() {
    // Only run once per day to avoid performance issues
    $last_check = get_option('anchor_up_registration_pages_last_check', 0);
    $current_time = time();
    
    // Check once per day
    if (($current_time - $last_check) < 86400) {
        return;
    }
    
    update_option('anchor_up_registration_pages_last_check', $current_time);
    
    // Define pages to create
    $pages_to_create = [
        [
            'title' => 'Anchor Up Promotion Registration',
            'slug' => 'anchor-up-promotion-registration',
            'template' => 'single-anchor-up-promotion-registration.php',
            'template_name' => 'Single Anchor Up Promotion Registration'
        ],
        [
            'title' => 'Anchor Up Website Registration',
            'slug' => 'anchor-up-website-registration',
            'template' => 'single-anchor-up-website-registration.php',
            'template_name' => 'Single Anchor Up Website Registration'
        ]
    ];
    
    foreach ($pages_to_create as $page_data) {
        // Check if page with this template already exists
        $existing_page = get_posts([
            'post_type' => 'page',
            'post_status' => ['publish', 'draft', 'private'],
            'meta_key' => '_wp_page_template',
            'meta_value' => $page_data['template'],
            'posts_per_page' => 1,
            'fields' => 'ids'
        ]);
        
        // If page doesn't exist, create it
        if (empty($existing_page)) {
            // Also check by slug to avoid duplicates
            $page_by_slug = get_page_by_path($page_data['slug']);
            
            if (!$page_by_slug) {
                $page_id = wp_insert_post([
                    'post_title' => $page_data['title'],
                    'post_name' => $page_data['slug'],
                    'post_status' => 'publish',
                    'post_type' => 'page',
                    'post_content' => '',
                    'meta_input' => [
                        '_wp_page_template' => $page_data['template']
                    ]
                ]);
                
                if (!is_wp_error($page_id) && $page_id) {
                    // Ensure template is set correctly
                    update_post_meta($page_id, '_wp_page_template', $page_data['template']);
                }
            } else {
                // Page exists but doesn't have the template - update it
                update_post_meta($page_by_slug->ID, '_wp_page_template', $page_data['template']);
            }
        } else {
            // Page exists with template - make sure it's published
            $page_id = $existing_page[0];
            $page = get_post($page_id);
            if ($page && $page->post_status !== 'publish') {
                wp_update_post([
                    'ID' => $page_id,
                    'post_status' => 'publish'
                ]);
            }
        }
    }
}

