<?php

/**
 * Anchor Up Promotion Hooks
 * WordPress hooks and filters for Anchor Up Promotions
 */

if (!defined('ABSPATH')) {
    exit;
}

// SendGrid Template Mappings
// Fallback template IDs if stw_config is not available
function anchor_up_get_sendgrid_template_id($template_key) {
    $template_mappings = [
        'connection-plus-admin-onboard-form' => 'd-8424a6f04a504ad3bf23fbf413a73339',
        'connection-plus-admin-initial-register-form' => 'd-9a8983f0ef794bfc9a6e6c59b2323b18',
        'anchor-up-foot-traffic-registration' => 'd-829d9a79a4ed441a843f386d95373c04',
        'wordpress-password-reset' => '', // Add your SendGrid template ID here
    ];
    
    // Try stw_config first
    if (function_exists('stw_config')) {
        $template_id = stw_config('sendgrid-template-mapping.' . $template_key);
        if (!empty($template_id)) {
            return $template_id;
        }
    }
    
    // Fallback to direct mapping
    if (isset($template_mappings[$template_key])) {
        return $template_mappings[$template_key];
    }
    
    return '';
}

// Register post types
add_action('init', 'anchor_up_promotion_register_post_types');
function anchor_up_promotion_register_post_types() {
    if (function_exists('register_extended_post_type')) {
        register_extended_post_type('promo-submission', [
            'supports' => ['title', 'custom-fields'],
            'menu_icon' => 'dashicons-megaphone'
        ]);
        register_extended_post_type('anchor-up-promotion', [
            'supports' => ['title', 'custom-fields', 'thumbnail', 'editor'],
            'menu_icon' => 'dashicons-megaphone'
        ]);
        register_extended_post_type('promo-signup', [
            'supports' => ['title', 'custom-fields'],
            'menu_icon' => 'dashicons-clipboard'
        ]);
    } else {
        // Fallback to standard WordPress register_post_type
        register_post_type('promo-submission', [
            'public' => true,
            'supports' => ['title', 'custom-fields'],
            'menu_icon' => 'dashicons-megaphone'
        ]);
        register_post_type('anchor-up-promotion', [
            'public' => true,
            'supports' => ['title', 'custom-fields', 'thumbnail', 'editor'],
            'menu_icon' => 'dashicons-megaphone'
        ]);
        register_post_type('promo-signup', [
            'public' => true,
            'supports' => ['title', 'custom-fields'],
            'menu_icon' => 'dashicons-clipboard'
        ]);
    }
}

// Change post type link domain (only if Store() function exists)
add_filter('post_type_link', 'anchor_up_promotion_change_post_type_link_domain', 10, 2);
function anchor_up_promotion_change_post_type_link_domain($permalink, $post) {
    if ('anchor-up-promotion' === $post->post_type && is_admin()) {
        // Only use Store() if the function exists
        if (function_exists('Store')) {
            $store = Store();
            if (method_exists($store, 'getDomainFromStoreId')) {
                $permalink = str_replace(get_site_url(), $store->getDomainFromStoreId('anchor-up', true), $permalink);
            }
        }
    }
    return $permalink;
}

// Auto Link Store Promo Submission to Anchor Up Store
add_filter('acf/load_field/name=_post_title', 'anchor_up_promotion_load_post_title_field', 10, 3);
function anchor_up_promotion_load_post_title_field($field) {
    $title = "Test";
    $field['value'] = $title;
    return $field;
}

// Auto Link Store Promo Submission to Anchor Up Promotion
add_filter('acf/load_field/name=anchor_up_promotion_relationship', 'anchor_up_promotion_load_promotion_relationship_field', 10, 3);
function anchor_up_promotion_load_promotion_relationship_field($field) {
    if (!is_admin()) {
        $current_promotion_post = get_post();
        if (isset($current_promotion_post)) {
            $field['instructions'] = '';
            $field['value'] = $current_promotion_post;
        }
    }
    return $field;
}

// Auto Link Store Promo Submission to Anchor Account Number
add_filter('acf/load_field/name=anchor_account_number', 'anchor_up_promotion_load_account_number_field', 10, 3);
function anchor_up_promotion_load_account_number_field($field) {
    if (!is_admin()) {
        if (class_exists('\STW\AnchorUp\AnchorUp')) {
            $store = \STW\AnchorUp\AnchorUp::isAnchorUpAdmin(true);
            $anchor_account_number = \STW\AnchorUp\AnchorUp::getAnchorAccountNumber($store);
            if (isset($anchor_account_number)) {
                $field['value'] = $anchor_account_number;
            }
        }
    }
    return $field;
}

// Auto Link Store Promo Submission to Anchor Autogenerated Store Id from Airtables
add_filter('acf/load_field/name=autogenerated_store_id', 'anchor_up_promotion_load_autogenerated_store_id_field', 10, 3);
function anchor_up_promotion_load_autogenerated_store_id_field($field) {
    if (!is_admin()) {
        if (class_exists('\STW\AnchorUp\AnchorUp')) {
            $store = \STW\AnchorUp\AnchorUp::isAnchorUpAdmin(true);
            $autogenerated_store_id = \STW\AnchorUp\AnchorUp::getAnchorUpAutoGeneratedStoreId($store);
            if (isset($autogenerated_store_id)) {
                $field['value'] = $autogenerated_store_id;
            }
        }
    }
    return $field;
}

// Auto-populate Store ID field
add_filter('acf/load_field/name=store_id', 'anchor_up_promotion_load_store_id_field', 10, 3);
function anchor_up_promotion_load_store_id_field($field) {
    if (!is_admin()) {
        if (class_exists('\STW\AnchorUp\AnchorUp')) {
            $store = \STW\AnchorUp\AnchorUp::isAnchorUpAdmin(true);
            if ($store && isset($store->autonumber)) {
                $field['value'] = $store->autonumber;
            }
        } elseif (function_exists('Store')) {
            $store = Store();
            if ($store && method_exists($store, 'autonumber')) {
                $field['value'] = $store->autonumber;
            } elseif ($store && isset($store->autonumber)) {
                $field['value'] = $store->autonumber;
            }
        }
    }
    return $field;
}

// Auto-populate Store Name field
add_filter('acf/load_field/name=store_name', 'anchor_up_promotion_load_store_name_field', 10, 3);
function anchor_up_promotion_load_store_name_field($field) {
    if (!is_admin()) {
        if (class_exists('\STW\AnchorUp\AnchorUp')) {
            $store = \STW\AnchorUp\AnchorUp::isAnchorUpAdmin(true);
            if ($store && isset($store->name)) {
                $field['value'] = $store->name;
            }
        } elseif (function_exists('Store')) {
            $store = Store();
            if ($store && method_exists($store, 'name')) {
                $field['value'] = $store->name;
            } elseif ($store && isset($store->name)) {
                $field['value'] = $store->name;
            }
        }
    }
    return $field;
}

// Auto-populate Store Name field for Specific Promotion Sign Ups
add_filter('acf/load_field/name=specific_signup_store_name', 'anchor_up_promotion_load_specific_signup_store_name_field', 10, 3);
function anchor_up_promotion_load_specific_signup_store_name_field($field) {
    if (!is_admin()) {
        if (class_exists('\STW\AnchorUp\AnchorUp')) {
            $store = \STW\AnchorUp\AnchorUp::isAnchorUpAdmin(true);
            if ($store && isset($store->name)) {
                $field['value'] = $store->name;
            }
        } elseif (function_exists('Store')) {
            $store = Store();
            if ($store && method_exists($store, 'name')) {
                $field['value'] = $store->name;
            } elseif ($store && isset($store->name)) {
                $field['value'] = $store->name;
            }
        }
    }
    return $field;
}

// Auto-populate Anchor Customer Number for Specific Promotion Sign Ups
add_filter('acf/load_field/name=specific_signup_anchor_customer_number', 'anchor_up_promotion_load_anchor_customer_number_field', 10, 3);
function anchor_up_promotion_load_anchor_customer_number_field($field) {
    if (!is_admin()) {
        if (class_exists('\STW\AnchorUp\AnchorUp')) {
            $anchor_account_number = \STW\AnchorUp\AnchorUp::getAnchorAccountNumber();
            if ($anchor_account_number) {
                $field['value'] = $anchor_account_number;
            }
        }
    }
    return $field;
}

// Auto-populate In Store Anchor Up Three Digit ID for Specific Promotion Sign Ups
add_filter('acf/load_field/name=in_store_anchor_up_three_digit_id', 'anchor_up_promotion_load_three_digit_id_field', 10, 3);
function anchor_up_promotion_load_three_digit_id_field($field) {
    if (!is_admin()) {
        if (class_exists('\STW\AnchorUp\AnchorUp')) {
            $store = \STW\AnchorUp\AnchorUp::isAnchorUpAdmin(true);
            if ($store) {
                // Try to get the three digit ID - this might be stored differently
                // You may need to adjust this based on how the ID is stored
                $autogenerated_store_id = \STW\AnchorUp\AnchorUp::getAnchorUpAutoGeneratedStoreId($store);
                if ($autogenerated_store_id) {
                    // Extract last 3 digits or use the ID as-is if it's already 3 digits
                    $three_digit_id = strlen($autogenerated_store_id) >= 3 ? substr($autogenerated_store_id, -3) : $autogenerated_store_id;
                    $field['value'] = $three_digit_id;
                }
            }
        }
    }
    return $field;
}

// Auto Link Specific Promotion Sign Up to Anchor Up Promotion
add_filter('acf/load_field/name=specific_signup_promotion_relationship', 'anchor_up_promotion_load_specific_signup_promotion_relationship_field', 10, 3);
function anchor_up_promotion_load_specific_signup_promotion_relationship_field($field) {
    if (!is_admin()) {
        // Get promotion ID from URL if available
        $promo_id = isset($_GET['promo-signup']) ? intval($_GET['promo-signup']) : null;
        
        // If not in URL, try to get from current post context
        if (!$promo_id) {
            $current_promotion_post = get_post();
            if ($current_promotion_post && $current_promotion_post->post_type === 'anchor-up-promotion') {
                $promo_id = $current_promotion_post->ID;
            }
        }
        
        if ($promo_id) {
            $field['value'] = $promo_id;
        }
    }
    return $field;
}

// Pre-populate the promotion relationship field value when form is loaded
add_filter('acf/load_value/name=specific_signup_promotion_relationship', 'anchor_up_promotion_load_specific_signup_promotion_relationship_value', 10, 3);
function anchor_up_promotion_load_specific_signup_promotion_relationship_value($value, $post_id, $field) {
    // Only pre-populate for new posts (when post_id is 'new_post' or 0)
    if ($post_id === 'new_post' || $post_id === 0 || empty($post_id)) {
        if (!is_admin()) {
            // Get promotion ID from URL if available
            $promo_id = isset($_GET['promo-signup']) ? intval($_GET['promo-signup']) : null;
            
            // If not in URL, try to get from current post context
            if (!$promo_id) {
                $current_promotion_post = get_post();
                if ($current_promotion_post && $current_promotion_post->post_type === 'anchor-up-promotion') {
                    $promo_id = $current_promotion_post->ID;
                }
            }
            
            if ($promo_id) {
                return $promo_id;
            }
        }
    }
    return $value;
}

// AJAX handler for promo signup form submission
add_action('wp_ajax_submit_promo_signup', 'anchor_up_promotion_ajax_submit_signup');
add_action('wp_ajax_nopriv_submit_promo_signup', 'anchor_up_promotion_ajax_submit_signup');
function anchor_up_promotion_ajax_submit_signup() {
    // Verify ACF form nonce first
    if (!acf_verify_nonce('acf_form')) {
        wp_send_json_error(array('message' => 'Security check failed. Please refresh the page and try again.'));
        return;
    }
    
    // Check if form data exists
    if (empty($_POST['_acf_form'])) {
        wp_send_json_error(array('message' => 'Form data missing.'));
        return;
    }
    
    // Load form configuration - try both methods
    $form = null;
    
    // Try to get form by ID first (if using registered forms)
    if (function_exists('acf_get_form')) {
        $form = acf_get_form($_POST['_acf_form']);
    }
    
    // Fallback to decrypting the form data
    if (!$form) {
        $form = json_decode(acf_decrypt($_POST['_acf_form']), true);
    }
    
    if (empty($form)) {
        wp_send_json_error(array('message' => 'Invalid form data.'));
        return;
    }
    
    // Run kses if needed
    if (isset($form['kses']) && $form['kses'] && isset($_POST['acf'])) {
        $_POST['acf'] = wp_kses_post_deep($_POST['acf']);
    }
    
    // Validate data
    $valid = acf_validate_save_post(true);
    if (!$valid) {
        // Get validation errors
        $errors = acf_get_validation_errors();
        $error_messages = array();
        if (!empty($errors)) {
            foreach ($errors as $error) {
                $error_messages[] = $error['message'];
            }
        }
        wp_send_json_error(array(
            'message' => 'Please correct the errors below.',
            'errors' => $error_messages
        ));
        return;
    }
    
    // Prepare post data
    $post_id = acf_maybe_get($form, 'post_id', 0);
    
    // Add global for backwards compatibility
    $GLOBALS['acf_form'] = $form;
    
    // Allow for custom save
    $post_id = apply_filters('acf/pre_save_post', $post_id, $form);
    
    // Save the post
    acf_save_post($post_id);
    
    // Restore form (potentially modified)
    $form = $GLOBALS['acf_form'];
    
    // Action hook
    do_action('acf/submit_form', $form, $post_id);
    
    // Return success
    wp_send_json_success(array(
        'message' => 'Sign-up submitted successfully!',
        'post_id' => $post_id
    ));
}

// Hide the promotion relationship field when it's pre-populated (front-end only)
add_filter('acf/prepare_field/name=specific_signup_promotion_relationship', 'anchor_up_promotion_hide_promotion_field', 10, 1);
function anchor_up_promotion_hide_promotion_field($field) {
    if (!is_admin()) {
        // Check if we're on a promotion page and the field has a value
        $promo_id = isset($_GET['promo-signup']) ? intval($_GET['promo-signup']) : null;
        
        if (!$promo_id) {
            $current_promotion_post = get_post();
            if ($current_promotion_post && $current_promotion_post->post_type === 'anchor-up-promotion') {
                $promo_id = $current_promotion_post->ID;
            }
        }
        
        // Hide the field if we have a promotion ID
        if ($promo_id) {
            return false; // Returning false hides the field
        }
    }
    return $field;
}

// Update post title on ACF save and save Store ID/Name
add_action('acf/save_post', 'anchor_up_promotion_update_post_title_on_save', 20);
function anchor_up_promotion_update_post_title_on_save($post_id) {
    if (isset($_POST['acf'])) {
        $post_type = get_post_type($post_id);
        
        // Handle promo-signup post type
        if ($post_type == "promo-signup") {
            // Get field keys
            $store_name_field = acf_get_field('specific_signup_store_name');
            $account_field = acf_get_field('specific_signup_anchor_customer_number');
            $three_digit_field = acf_get_field('in_store_anchor_up_three_digit_id');
            $promotion_field = acf_get_field('specific_signup_promotion_relationship');
            
            $store_name_key = $store_name_field ? $store_name_field['key'] : 'field_specific_signup_store_name';
            $account_key = $account_field ? $account_field['key'] : 'field_specific_signup_anchor_customer_number';
            $three_digit_key = $three_digit_field ? $three_digit_field['key'] : 'field_in_store_anchor_up_three_digit_id';
            $promotion_key = $promotion_field ? $promotion_field['key'] : 'field_specific_signup_promotion_relationship';
            
            // Get values from POST data first (before ACF saves), then fallback to get_field
            $store_name = '';
            $anchor_customer_number = '';
            $three_digit_id = '';
            $promo_id = null;
            
            if (isset($_POST['acf'][$store_name_key])) {
                $store_name = sanitize_text_field($_POST['acf'][$store_name_key]);
            } else {
                $store_name = get_field('specific_signup_store_name', $post_id);
            }
            
            if (isset($_POST['acf'][$account_key])) {
                $anchor_customer_number = sanitize_text_field($_POST['acf'][$account_key]);
            } else {
                $anchor_customer_number = get_field('specific_signup_anchor_customer_number', $post_id);
            }
            
            if (isset($_POST['acf'][$three_digit_key])) {
                $three_digit_id = sanitize_text_field($_POST['acf'][$three_digit_key]);
            } else {
                $three_digit_id = get_field('in_store_anchor_up_three_digit_id', $post_id);
            }
            
            if (isset($_POST['acf'][$promotion_key])) {
                $promo_id = intval($_POST['acf'][$promotion_key]);
            } else {
                $promotion = get_field('specific_signup_promotion_relationship', $post_id);
                if ($promotion) {
                    if (is_array($promotion)) {
                        $promo_id = is_numeric($promotion[0]) ? intval($promotion[0]) : (is_object($promotion[0]) ? $promotion[0]->ID : null);
                    } elseif (is_object($promotion)) {
                        $promo_id = $promotion->ID;
                    } elseif (is_numeric($promotion)) {
                        $promo_id = intval($promotion);
                    }
                }
            }
            
            // Get promotion name
            $promo_name = '';
            if ($promo_id) {
                $promo_name = get_the_title($promo_id);
            }
            
            // Build post title in format: Store Name - Account Number - 3 Digit Code - Promo Name
            $title_parts = array();
            
            if (!empty($store_name)) {
                $title_parts[] = $store_name;
            }
            
            if (!empty($anchor_customer_number)) {
                $title_parts[] = $anchor_customer_number;
            }
            
            if (!empty($three_digit_id)) {
                $title_parts[] = $three_digit_id;
            }
            
            if (!empty($promo_name)) {
                $title_parts[] = $promo_name;
            }
            
            // Only update if we have at least one part
            if (!empty($title_parts)) {
                $post_title = implode(' - ', $title_parts);
                
                // Update the post title
                $post_data = array(
                    'ID' => $post_id,
                    'post_title' => $post_title,
                );
                
                // Remove this hook temporarily to avoid infinite loop
                remove_action('acf/save_post', 'anchor_up_promotion_update_post_title_on_save', 20);
                wp_update_post($post_data);
                add_action('acf/save_post', 'anchor_up_promotion_update_post_title_on_save', 20);
            }
        }
        
        if ($post_type == "promo-submission") {
            $store_id = '';
            $store_name = '';
            
            // Get Store ID and Name from form or store object
            // ACF uses field keys in $_POST['acf']
            if (isset($_POST['acf']['field_store_id_promo'])) {
                $store_id = sanitize_text_field($_POST['acf']['field_store_id_promo']);
            }
            if (isset($_POST['acf']['field_store_name_promo'])) {
                $store_name = sanitize_text_field($_POST['acf']['field_store_name_promo']);
            }
            
            // If not in form, try to get from store object
            if (empty($store_id) || empty($store_name)) {
                if (class_exists('\STW\AnchorUp\AnchorUp')) {
                    $store = \STW\AnchorUp\AnchorUp::isAnchorUpAdmin(true);
                    if ($store) {
                        if (empty($store_id) && isset($store->autonumber)) {
                            $store_id = $store->autonumber;
                        }
                        if (empty($store_name) && isset($store->name)) {
                            $store_name = $store->name;
                        }
                    }
                } elseif (function_exists('Store')) {
                    $store = Store();
                    if ($store) {
                        if (empty($store_id)) {
                            $store_id = method_exists($store, 'autonumber') ? $store->autonumber : (isset($store->autonumber) ? $store->autonumber : '');
                        }
                        if (empty($store_name)) {
                            $store_name = method_exists($store, 'name') ? $store->name : (isset($store->name) ? $store->name : '');
                        }
                    }
                }
            }
            
            // Save Store ID and Store Name to post meta
            if (!empty($store_id)) {
                update_post_meta($post_id, 'store_id', $store_id);
                // Also update ACF field if it exists
                update_field('store_id', $store_id, $post_id);
            }
            if (!empty($store_name)) {
                update_post_meta($post_id, 'store_name', $store_name);
                // Also update ACF field if it exists
                update_field('store_name', $store_name, $post_id);
            }
            
            // Update post title
            if (class_exists('\STW\AnchorUp\AnchorUp')) {
                $store = \STW\AnchorUp\AnchorUp::isAnchorUpAdmin(true);

                $promo_id = isset($_POST['acf']['field_64381a6072103']) ? $_POST['acf']['field_64381a6072103'] : null;

                if ($promo_id) {
                    $promo_post = get_post($promo_id);
                    if ($promo_post) {
                        $promo_post_title = $promo_post->post_title;
                        $post_title = ($store_name ?: ($store ? $store->name : '')) . ' - Acct #: ' . ($store ? $store->anchor_customer_id : '') . ' - Store Id: ' . ($store_id ?: ($store ? $store->autonumber : '')) . ' - Promo: ' . $promo_post_title;

                        $post_data = array(
                            'ID' => $post_id,
                            'post_title' => $post_title,
                        );

                        wp_update_post($post_data);
                    }
                }
            }
        }
    }
}

// Custom validation rule to check for overlapping date ranges
add_filter('acf/validate_value/name=promotion_start_date', 'anchor_up_promotion_validate_start_date', 10, 4);
function anchor_up_promotion_validate_start_date($valid, $value, $field, $input) {
    $post_id = isset($_POST['post_ID']) ? $_POST['post_ID'] : 0;
    $meta_key_start = 'promotion_start_date';
    $meta_key_end = 'promotion_end_date';

    $start_date = strtotime(get_field($meta_key_start, $post_id));
    $end_date = strtotime(get_field($meta_key_end, $post_id));

    if ($start_date && $end_date && $start_date >= $end_date) {
        $valid = 'Start date must be before end date.';
    }

    // Check for overlapping date ranges
    $query = new WP_Query(array(
        'post_type' => 'anchor-up-promotion',
        'post__not_in' => array($post_id),
        'meta_query' => array(
            'relation' => 'AND',
            array(
                'key' => $meta_key_start,
                'value' => $value,
                'compare' => '<=',
                'type' => 'DATE',
            ),
            array(
                'key' => $meta_key_end,
                'value' => $value,
                'compare' => '>=',
                'type' => 'DATE',
            ),
        ),
    ));

    if ($query->have_posts()) {
        $overlapping_posts = array();
        while ($query->have_posts()) {
            $query->the_post();
            $post_title = get_the_title();
            $post_id_overlap = get_the_ID();
            $edit_link = get_edit_post_link($post_id_overlap);
            $overlapping_posts[] = "<a href='$edit_link' target='_blank'>$post_title</a>";
        }
        wp_reset_query();

        $overlapping_posts_html = implode(', ', $overlapping_posts);
        $valid = "Date range overlaps with the following existing entries: $overlapping_posts_html";
    }

    return $valid;
}

// Add custom columns to Anchor Up Promotion admin list
add_filter('manage_anchor-up-promotion_posts_columns', 'anchor_up_promotion_add_admin_columns');
function anchor_up_promotion_add_admin_columns($columns) {
    // Insert Promotion Start Date after title
    $new_columns = array();
    foreach ($columns as $key => $value) {
        $new_columns[$key] = $value;
        if ($key === 'title') {
            $new_columns['promotion_start_date'] = 'Promotion Start Date';
            $new_columns['promotion_end_date'] = 'Promotion End Date';
            $new_columns['sign_ups_count'] = 'Sign Ups / Max Kits';
        }
    }
    return $new_columns;
}

// Populate custom column content
add_action('manage_anchor-up-promotion_posts_custom_column', 'anchor_up_promotion_populate_admin_columns', 10, 2);
function anchor_up_promotion_populate_admin_columns($column, $post_id) {
    switch ($column) {
        case 'promotion_start_date':
            $start_date = get_field('promotion_start_date', $post_id);
            if ($start_date) {
                // Format the date nicely
                $date_timestamp = strtotime($start_date);
                $today = strtotime(date('Ymd'));
                
                echo '<strong>' . esc_html($start_date) . '</strong>';
                
                // Add status indicator
                $end_date = get_field('promotion_end_date', $post_id);
                if ($end_date) {
                    $end_timestamp = strtotime($end_date);
                    if ($today >= $date_timestamp && $today <= $end_timestamp) {
                        echo '<br><span style="color: #10b981; font-size: 11px;">● Active Now</span>';
                    } elseif ($today < $date_timestamp) {
                        $days_until = ceil(($date_timestamp - $today) / 86400);
                        echo '<br><span style="color: #f59e0b; font-size: 11px;">● Starts in ' . $days_until . ' day' . ($days_until != 1 ? 's' : '') . '</span>';
                    } elseif ($today > $end_timestamp) {
                        echo '<br><span style="color: #6b7280; font-size: 11px;">● Ended</span>';
                    }
                }
            } else {
                echo '<span style="color: #9ca3af;">—</span>';
            }
            break;
            
        case 'promotion_end_date':
            $end_date = get_field('promotion_end_date', $post_id);
            if ($end_date) {
                echo esc_html($end_date);
            } else {
                echo '<span style="color: #9ca3af;">—</span>';
            }
            break;
            
        case 'sign_ups_count':
            $max_kits = get_field('max_numbers_of_kits', $post_id);
            $max_kits = $max_kits ? intval($max_kits) : 0;
            
            // Count sign-ups for this promotion
            $sign_ups_query = new WP_Query(array(
                'post_type' => 'promo-signup',
                'posts_per_page' => -1,
                'meta_query' => array(
                    array(
                        'key' => 'specific_signup_promotion_relationship',
                        'value' => $post_id,
                        'compare' => '=',
                    ),
                ),
                'fields' => 'ids',
            ));
            
            $sign_ups_count = $sign_ups_query->found_posts;
            $remaining = $max_kits - $sign_ups_count;
            
            // Create a unique ID for this row's counter
            $counter_id = 'signup-counter-' . $post_id;
            
            if ($max_kits > 0) {
                // Calculate percentage
                $percentage = ($sign_ups_count / $max_kits) * 100;
                $percentage = min(100, max(0, $percentage));
                
                // Color coding based on availability
                if ($remaining <= 0) {
                    $color = '#ef4444'; // Red - sold out
                    $status = 'Sold Out';
                } elseif ($remaining <= ($max_kits * 0.1)) {
                    $color = '#f59e0b'; // Orange - low stock
                    $status = 'Low Stock';
                } else {
                    $color = '#10b981'; // Green - available
                    $status = 'Available';
                }
                
                echo '<div id="' . esc_attr($counter_id) . '" class="signup-counter" data-post-id="' . esc_attr($post_id) . '" data-max-kits="' . esc_attr($max_kits) . '">';
                echo '<div style="font-weight: 600; font-size: 14px; margin-bottom: 4px;">';
                echo '<span style="color: ' . esc_attr($color) . ';">' . esc_html($sign_ups_count) . ' / ' . esc_html($max_kits) . '</span>';
                echo '</div>';
                echo '<div style="font-size: 11px; color: #6b7280; margin-bottom: 4px;">';
                echo '<span style="color: ' . esc_attr($color) . ';">● ' . esc_html($status) . '</span>';
                echo ' <span style="color: #9ca3af;">(' . esc_html($remaining) . ' remaining)</span>';
                echo '</div>';
                echo '<div style="width: 100%; background: #e5e7eb; height: 6px; border-radius: 3px; overflow: hidden; margin-top: 4px;">';
                echo '<div style="background: ' . esc_attr($color) . '; height: 100%; width: ' . esc_attr($percentage) . '%; transition: width 0.3s ease;"></div>';
                echo '</div>';
                echo '</div>';
            } else {
                echo '<span style="color: #9ca3af;">Max kits not set</span>';
            }
            wp_reset_postdata();
            break;
    }
}

// Make columns sortable
add_filter('manage_edit-anchor-up-promotion_sortable_columns', 'anchor_up_promotion_make_columns_sortable');
function anchor_up_promotion_make_columns_sortable($columns) {
    $columns['promotion_start_date'] = 'promotion_start_date';
    $columns['promotion_end_date'] = 'promotion_end_date';
    return $columns;
}

// Handle the sorting
add_action('pre_get_posts', 'anchor_up_promotion_handle_admin_sorting');
function anchor_up_promotion_handle_admin_sorting($query) {
    // Only run in admin and for our post type
    if (!is_admin() || !$query->is_main_query()) {
        return;
    }
    
    if ($query->get('post_type') !== 'anchor-up-promotion') {
        return;
    }
    
    // Get the orderby value
    $orderby = $query->get('orderby');
    
    // Set default sorting to promotion_start_date ASC (most upcoming first)
    if (empty($orderby) || $orderby === 'date') {
        $query->set('meta_key', 'promotion_start_date');
        $query->set('orderby', 'meta_value');
        $query->set('order', 'ASC');
    }
    
    // Handle custom column sorting
    if ($orderby === 'promotion_start_date' || $orderby === 'promotion_end_date') {
        $query->set('meta_key', $orderby);
        $query->set('orderby', 'meta_value');
        
        // Get the order (default to ASC for start date, DESC for end date)
        $order = $query->get('order');
        if (empty($order)) {
            $order = ($orderby === 'promotion_start_date') ? 'ASC' : 'DESC';
            $query->set('order', $order);
        }
    }
}

// Add custom columns to Promo Signup admin list
add_filter('manage_promo-signup_posts_columns', 'anchor_up_promotion_add_signup_admin_columns');
function anchor_up_promotion_add_signup_admin_columns($columns) {
    // Insert custom columns after title
    $new_columns = array();
    foreach ($columns as $key => $value) {
        $new_columns[$key] = $value;
        if ($key === 'title') {
            $new_columns['store_name'] = 'Store Name';
            $new_columns['account_number'] = 'Account Number';
            $new_columns['three_digit_code'] = '3 Digit Code';
            $new_columns['promotion'] = 'Promotion';
        }
    }
    return $new_columns;
}

// Populate custom column content for Promo Signup
add_action('manage_promo-signup_posts_custom_column', 'anchor_up_promotion_populate_signup_admin_columns', 10, 2);
function anchor_up_promotion_populate_signup_admin_columns($column, $post_id) {
    switch ($column) {
        case 'store_name':
            $store_name = get_field('specific_signup_store_name', $post_id);
            if ($store_name) {
                echo '<strong>' . esc_html($store_name) . '</strong>';
            } else {
                echo '<span style="color: #9ca3af;">—</span>';
            }
            break;
            
        case 'account_number':
            $account_number = get_field('specific_signup_anchor_customer_number', $post_id);
            if ($account_number) {
                echo esc_html($account_number);
            } else {
                echo '<span style="color: #9ca3af;">—</span>';
            }
            break;
            
        case 'three_digit_code':
            $three_digit = get_field('in_store_anchor_up_three_digit_id', $post_id);
            if ($three_digit) {
                echo '<code style="background: #f3f4f6; padding: 2px 6px; border-radius: 3px; font-size: 12px;">' . esc_html($three_digit) . '</code>';
            } else {
                echo '<span style="color: #9ca3af;">—</span>';
            }
            break;
            
        case 'promotion':
            $promotion = get_field('specific_signup_promotion_relationship', $post_id);
            if ($promotion) {
                if (is_array($promotion)) {
                    $promotion = $promotion[0];
                }
                $promotion_id = is_object($promotion) ? $promotion->ID : $promotion;
                $promotion_title = is_object($promotion) ? $promotion->post_title : get_the_title($promotion_id);
                $edit_link = get_edit_post_link($promotion_id);
                echo '<a href="' . esc_url($edit_link) . '">' . esc_html($promotion_title) . '</a>';
            } else {
                echo '<span style="color: #9ca3af;">—</span>';
            }
            break;
    }
}

// Add filter dropdown for Promotion
add_action('restrict_manage_posts', 'anchor_up_promotion_add_signup_promotion_filter', 10, 2);
function anchor_up_promotion_add_signup_promotion_filter($post_type, $which = '') {
    global $typenow;
    
    // Use $post_type parameter if available, otherwise fall back to $typenow
    $current_post_type = $post_type ? $post_type : $typenow;
    
    // Only show on promo-signup post type
    if ($current_post_type !== 'promo-signup') {
        return;
    }
    
    // Only show on top filter area
    if ($which !== 'top') {
        return;
    }
    
    // Get all promotions
    $promotions = get_posts(array(
        'post_type' => 'anchor-up-promotion',
        'posts_per_page' => -1,
        'orderby' => 'title',
        'order' => 'ASC',
        'post_status' => 'any',
    ));
    
    if (empty($promotions)) {
        return;
    }
    
    // Get selected promotion from URL
    $selected = isset($_GET['filter_by_promotion']) ? intval($_GET['filter_by_promotion']) : '';
    
    // Add label and select
    echo '<label for="filter_by_promotion" class="screen-reader-text">' . __('Filter by Promotion', 'e3local') . '</label>';
    echo '<select name="filter_by_promotion" id="filter_by_promotion" style="margin-right: 10px;">';
    echo '<option value="">' . __('All Promotions', 'e3local') . '</option>';
    
    foreach ($promotions as $promotion) {
        $selected_attr = selected($selected, $promotion->ID, false);
        echo '<option value="' . esc_attr($promotion->ID) . '" ' . $selected_attr . '>' . esc_html($promotion->post_title) . '</option>';
    }
    
    echo '</select>';
}

// Filter posts by Promotion
add_action('pre_get_posts', 'anchor_up_promotion_filter_signup_by_promotion');
function anchor_up_promotion_filter_signup_by_promotion($query) {
    global $pagenow, $typenow;
    
    // Only run in admin and for promo-signup post type
    if (!is_admin() || !$query->is_main_query() || $pagenow !== 'edit.php' || $typenow !== 'promo-signup') {
        return;
    }
    
    // Check if filter is set
    if (isset($_GET['filter_by_promotion']) && !empty($_GET['filter_by_promotion'])) {
        $promotion_id = intval($_GET['filter_by_promotion']);
        
        // Add meta query to filter by promotion
        $meta_query = $query->get('meta_query');
        if (!is_array($meta_query)) {
            $meta_query = array();
        }
        
        $meta_query[] = array(
            'key' => 'specific_signup_promotion_relationship',
            'value' => $promotion_id,
            'compare' => '=',
        );
        
        $query->set('meta_query', $meta_query);
    }
}

// Anchor Up Register Form
add_action('init', 'anchor_up_promotion_setup_register_form_hook');
function anchor_up_promotion_setup_register_form_hook() {
    // Check if Gravity Forms is active
    if (!class_exists('RGFormsModel')) {
        return;
    }
    
    $anchor_up_register_form_id = RGFormsModel::get_form_id("Anchor Up - Register");
    
    if (!$anchor_up_register_form_id) {
        return;
    }
    
    $anchor_up_register_form = 'gform_after_submission_' . $anchor_up_register_form_id;
    
    add_action($anchor_up_register_form, 'anchor_up_promotion_handle_register_form_submission', 10, 2);
}

function anchor_up_promotion_handle_register_form_submission($entry, $form) {
    $user_email = strtolower(rgar($entry, '39'));
    $form_id = rgar($entry, 'form_id');
    $form_date_submitted = rgar($entry, 'date_created');
    $entry_id = rgar($entry, 'id');
    $source_url = rgar($entry, 'source_url');
    $program = rgar($entry, '26');
    
    $pos = rgar($entry, '28');
    $other_pos = rgar($entry, '29');
    
    if ($other_pos) {
        $pos = $other_pos;
    }
    
    $current_user = wp_get_current_user();
    $first_name = $current_user->user_firstname;
    $last_name = $current_user->user_lastname;
    
    $new_store_onboard = array(
        'Name' => rgar($entry, '4'),
        'URL' => rgar($entry, '27'),
        'first_name' => $first_name,
        'last_name' => $last_name,
        'email' => $user_email,
        'anchor_customer_id' => rgar($entry, '3'),
        'pos_system' => $pos,
        'bookstore_type' => rgar($entry, '20'),
        'program_interested' => $program,
        'Status' => 'Pending Approval',
        'Notes' => rgar($entry, '30'),
        'has_social_media' => rgar($entry, '32'),
        'uses_social_media_agency' => rgar($entry, '33'),
        'interested_in_him_first_media' => rgar($entry, '34'),
        'questions' => rgar($entry, '35'),
        'current_website_url' => rgar($entry, '27'),
        'facebook_url' => rgar($entry, '37'),
        'instagram_username' => rgar($entry, '38'),
        'street_address' => rgar($entry, '36.1') . ' ' . rgar($entry, '36.2'),
        'city' => rgar($entry, '36.3'),
        'state' => rgar($entry, '36.4'),
        'zipcode' => rgar($entry, '36.5'),
        'marketing_group' => rgar($entry, '44'),
        'anchor_ship_to_id' => rgar($entry, '47'),
        'street_address' => rgar($entry, '45.1'),
        'city' => rgar($entry, '45.3'),
        'state' => rgar($entry, '45.4'),
        'zipcode' => rgar($entry, '45.5'),
        'country' => rgar($entry, '45.6')
    );
    
    // Save to Airtable - Tab: Connection Plus
    if (function_exists('anchor_up_airtable_post_data')) {
        $post = anchor_up_airtable_post_data($new_store_onboard, 'anchor_up_foot_traffic_stores');
    } elseif (class_exists('STW\Airtable\Airtable')) {
        $post = \STW\Airtable\Airtable::postData($new_store_onboard, 'anchor_up_foot_traffic_stores');
    }
    
    // Create in Customer.io
    $form_details = [
        'form-id' => $form_id,
        'form-title' => 'anchor-up-register',
        'store_name' => rgar($entry, '4'),
        'site_url' => rgar($entry, '27'),
        'anchor_customer_id' => rgar($entry, '3'),
        'pos_system' => $pos,
        'bookstore_type' => rgar($entry, '20'),
        'program_interested' => $program,
        'has_social_media' => rgar($entry, '32'),
        'uses_social_media_agency' => rgar($entry, '33'),
        'interested_in_him_first_media' => rgar($entry, '34'),
        'questions' => rgar($entry, '35'),
    ];
    
    // Send email via Sendgrid if available
    $template_id = anchor_up_get_sendgrid_template_id('anchor-up-foot-traffic-registration');
    
    $sendgrid_response_data = null;
    if ($template_id) {
        if (function_exists('Store') && function_exists('anchor_up_sendgrid_send_email')) {
            $store_data = Store();
            if ($store_data && method_exists($store_data, 'send_as_email')) {
                $res = anchor_up_sendgrid_send_email(
                    $store_data->send_as_email, 
                    $store_data->name, 
                    $user_email, 
                    $template_id, 
                    $form_details
                );
                
                // Store response for JavaScript output
                if ($res) {
                    try {
                        $status_code = method_exists($res, 'statusCode') ? $res->statusCode() : null;
                        $response_body = method_exists($res, 'body') ? $res->body() : null;
                        $sendgrid_response_data = [
                            'status_code' => $status_code,
                            'body' => $response_body,
                            'from' => $store_data->send_as_email,
                            'to' => $user_email,
                            'template_id' => $template_id
                        ];
                    } catch (\Exception $e) {
                        $sendgrid_response_data = ['error' => $e->getMessage()];
                    }
                }
            }
        } elseif (class_exists('STW\Email\SendGrid')) {
            $store_data = Store();
            if ($store_data && method_exists($store_data, 'send_as_email')) {
                $res = \STW\Email\SendGrid::sendEmail(
                    $store_data->send_as_email, 
                    $store_data->name, 
                    $user_email, 
                    $template_id, 
                    $form_details
                );
                
                // Store response for JavaScript output
                if ($res) {
                    try {
                        $status_code = method_exists($res, 'statusCode') ? $res->statusCode() : null;
                        $response_body = method_exists($res, 'body') ? $res->body() : null;
                        $sendgrid_response_data = [
                            'status_code' => $status_code,
                            'body' => $response_body,
                            'from' => $store_data->send_as_email,
                            'to' => $user_email,
                            'template_id' => $template_id
                        ];
                    } catch (\Exception $e) {
                        $sendgrid_response_data = ['error' => $e->getMessage()];
                    }
                }
            }
        }
    }
    
    // Store SendGrid response and output to console
    if ($sendgrid_response_data) {
        gform_update_meta($entry_id, 'sendgrid_response', json_encode($sendgrid_response_data));
        
        // Add JavaScript to output console log via Gravity Forms confirmation filter
        add_filter('gform_confirmation_' . $form_id, function($confirmation, $form, $entry) use ($sendgrid_response_data) {
            $js_data = json_encode($sendgrid_response_data);
            $script = '<script>
                console.log("SendGrid Email Response:", ' . $js_data . ');
                // Also listen for AJAX confirmations
                if (typeof jQuery !== "undefined") {
                    jQuery(document).on("gform_confirmation_loaded", function(event, formId) {
                        if (formId == ' . $form['id'] . ') {
                            console.log("SendGrid Email Response:", ' . $js_data . ');
                        }
                    });
                }
            </script>';
            return $confirmation . $script;
        }, 10, 3);
    }
    
    // Build HTML email content
    $html = '<h1>New Anchor Up Foot Traffic Registration</h1>';
    $html .= '<h2>View This New Entry in Airtables</h2>';
    $html .= '<p>A new store has registered for Anchor Up. Please check the Anchor Up Dashboard for more details.</p>';
    $html .= '<p>Store Name: ' . esc_html(rgar($entry, '4')) . '</p>';
    $html .= '<p>Store URL: ' . esc_html(rgar($entry, '27')) . '</p>';
    $html .= '<p>Anchor Customer ID: ' . esc_html(rgar($entry, '3')) . '</p>';
    $html .= '<p>POS System: ' . esc_html($pos) . '</p>';
    $html .= '<p>Bookstore Type: ' . esc_html(rgar($entry, '20')) . '</p>';
    $html .= '<p>Program Interested: ' . esc_html($program) . '</p>';
    $html .= '<p>Has Social Media: ' . esc_html(rgar($entry, '32')) . '</p>';
    $html .= '<p>Uses Social Media Agency: ' . esc_html(rgar($entry, '33')) . '</p>';
    $html .= '<p>Interested in Him First Media: ' . esc_html(rgar($entry, '34')) . '</p>';
    $html .= '<p>Current Website URL: ' . esc_html(rgar($entry, '27')) . '</p>';
    $html .= '<p>Facebook URL: ' . esc_html(rgar($entry, '37')) . '</p>';
    $html .= '<p>Instagram Username: ' . esc_html(rgar($entry, '38')) . '</p>';
    $html .= '<p>Street Address: ' . esc_html(rgar($entry, '36.1') . ' ' . rgar($entry, '36.2')) . '</p>';
    $html .= '<p>City: ' . esc_html(rgar($entry, '36.3')) . '</p>';
    $html .= '<p>State: ' . esc_html(rgar($entry, '36.4')) . '</p>';
    $html .= '<p>Zipcode: ' . esc_html(rgar($entry, '36.5')) . '</p>';
    $html .= '<p>Marketing Group: ' . esc_html(rgar($entry, '44')) . '</p>';
    $html .= '<p>anchor_ship_to_id: ' . esc_html(rgar($entry, '47')) . '</p>';
    $html .= '<p>street_address: ' . esc_html(rgar($entry, '45.1')) . '</p>';
    $html .= '<p>city: ' . esc_html(rgar($entry, '45.3')) . '</p>';
    $html .= '<p>state: ' . esc_html(rgar($entry, '45.4')) . '</p>';
    $html .= '<p>zipcode: ' . esc_html(rgar($entry, '45.5')) . '</p>';
    $html .= '<p>country: ' . esc_html(rgar($entry, '45.6')) . '</p>';
    $html .= '<p>Questions: ' . esc_html(rgar($entry, '35')) . '</p>';
    
    $admin_emails = [
        'anchorup@anchordistributors.com',
        'scott.whitaker@anchordistributors.com',
        'customercare@anchordistributors.com'
    ];
    
    // Set email content type to HTML
    add_filter('wp_mail_content_type', function ($content_type) {
        return 'text/html';
    });
    
    // Send emails to admin addresses
    foreach ($admin_emails as $email) {
        wp_mail($email, 'Anchor Up Registration - ' . esc_html(rgar($entry, '4')), $html);
    }
    
    // Remove the content type filter after sending
    remove_filter('wp_mail_content_type', function ($content_type) {
        return 'text/html';
    });
    
    // Clear Airtable cache
    delete_option('_transient_stw.airtable.anchor_up_foot_traffic_stores');
}

// Anchor Up - Official Onboarding Form
add_action('init', 'anchor_up_promotion_setup_website_onboarding_form_hook');
function anchor_up_promotion_setup_website_onboarding_form_hook() {
    // Check if Gravity Forms is active
    if (!class_exists('RGFormsModel')) {
        return;
    }
    
    $on_boarding_form_id = RGFormsModel::get_form_id("Anchor Up - Official Onboarding");
    
    if (!$on_boarding_form_id) {
        return;
    }
    
    $on_boarding_form = 'gform_after_submission_' . $on_boarding_form_id;
    
    add_action($on_boarding_form, 'anchor_up_promotion_handle_website_onboarding_form_submission', 10, 2);
}

// Helper function for dd() (dump and die) - Laravel-style debugging
if (!function_exists('dd')) {
    function dd(...$vars) {
        foreach ($vars as $var) {
            echo '<pre style="background: #f4f4f4; padding: 20px; margin: 20px; border: 2px solid #333; border-radius: 5px; overflow: auto; max-width: 90%;">';
            var_dump($var);
            echo '</pre>';
        }
        die();
    }
}

function anchor_up_promotion_handle_website_onboarding_form_submission($entry, $form) {
    $user_email = strtolower(rgar($entry, '2'));
    $form_id = rgar($entry, 'form_id');
    $form_date_submitted = rgar($entry, 'date_created');
    $entry_id = rgar($entry, 'id');
    $source_url = rgar($entry, 'source_url');
    
    $programs = array(
        rgar($entry, '17.1'),
        rgar($entry, '17.2')
    );
    $programs = implode(', ', array_filter($programs));
    
    $admin_email = rgar($entry, '19');
    
    $new_store_onboard = array(
        'Name' => rgar($entry, '4'),
        'URL' => rgar($entry, '1'),
        'site_type' => 'Bookstore',
        'anchor_customer_id' => rgar($entry, '3'),
        'Store_Association' => rgar($entry, '5'),
        'pos_system' => rgar($entry, '42'),
        'pos_notes' => rgar($entry, '43'),
        'Account_First_Name' => rgar($entry, '6'),
        'Account_Last_Name' => rgar($entry, '7'),
        'Store_In_Store_Phone_Number' => rgar($entry, '9'),
        'Store_Street_Address' => rgar($entry, '18.1'),
        'Store_Street_Address_2' => rgar($entry, '18.2'),
        'Store_City' => rgar($entry, '18.3'),
        'Store_State' => rgar($entry, '18.4'),
        'Store_Zipcode' => rgar($entry, '18.5'),
        'Admin_Email' => rgar($entry, '19'),
        'Send_As_Email' => $admin_email,
        'Support_Email' => rgar($entry, '21'),
        'Webmaster - Contact for DNS' => rgar($entry, '22'),
        // Added a Hashtag, cause the new color plugin doesnt add it.
        'Primary_Theme_Color' => "#" . rgar($entry, '40'),
        'Accent_Theme_Color' => "#" . rgar($entry, '41'),
        'Logo_url' => rgar($entry, '25'),
        'Paperwork_Logo_url' => rgar($entry, '26'),
        'Address_Label_Logo_url' => rgar($entry, '27'),
        'Store_Hours' => rgar($entry, '28'),
        'store_about_us_description' => rgar($entry, '31'),
        'store_exterior_image_url' => rgar($entry, '29'),
        'store_interior_image_url' => rgar($entry, '30'),
        'store_short_intro' => rgar($entry, '32'),
        'store_tagline' => rgar($entry, '34'),
        'In_Store_Services' => rgar($entry, '33'),
        'store_facebook_url' => rgar($entry, '35'),
        'store_instagram_username' => rgar($entry, '36'),
        'store_twitter_username' => rgar($entry, '37'),
        'store_covid_notice' => rgar($entry, '38'),
        'store_additional_information' => rgar($entry, '39')
    );
    
    // Save to Airtable - Tab: Connection Plus
    if (function_exists('anchor_up_airtable_post_data')) {
        $post = anchor_up_airtable_post_data($new_store_onboard, 'connection_plus');
    } elseif (class_exists('STW\Airtable\Airtable')) {
        $post = \STW\Airtable\Airtable::postData($new_store_onboard, 'connection_plus');
    }
    
    $form_details = [
        'form-id' => $form_id,
        'form-title' => 'connection-plus-onboarding',
        'entry-id' => $entry_id,
        'form-date-submitted' => $form_date_submitted,
        'message' => rgar($entry, '3'),
        'source-url' => $source_url,
        'URL' => rgar($entry, '1'),
        'anchor_customer_id' => rgar($entry, '3'),
        'bookstore_name' => rgar($entry, '4'),
        'bookstore association' => rgar($entry, '5'),
        'account_first_name' => rgar($entry, '6'),
        'account_last_name' => rgar($entry, '7'),
        'account_email_address' => rgar($entry, '8'),
        'store_phone_number' => rgar($entry, '9'),
        'store_address_1' => rgar($entry, '18.1'),
        'store_address_2' => rgar($entry, '18.2'),
        'store_city' => rgar($entry, '18.3'),
        'store_state' => rgar($entry, '18.4'),
        'store_zipcode' => rgar($entry, '18.5')
    ];
    
    // Send email via Sendgrid if available
    $template_id = anchor_up_get_sendgrid_template_id('connection-plus-admin-onboard-form');
    
    $sendgrid_response_data = null;
    if ($template_id) {
        if (function_exists('Store') && function_exists('anchor_up_sendgrid_send_email')) {
            $store_data = Store();
            if ($store_data && method_exists($store_data, 'send_as_email')) {
                $res = anchor_up_sendgrid_send_email(
                    $store_data->send_as_email, 
                    $store_data->name, 
                    $admin_email, 
                    $template_id, 
                    $form_details
                );
                
                // Store response for JavaScript output
                if ($res) {
                    try {
                        $status_code = method_exists($res, 'statusCode') ? $res->statusCode() : null;
                        $response_body = method_exists($res, 'body') ? $res->body() : null;
                        $sendgrid_response_data = [
                            'status_code' => $status_code,
                            'body' => $response_body,
                            'from' => $store_data->send_as_email,
                            'to' => $admin_email,
                            'template_id' => $template_id
                        ];
                    } catch (\Exception $e) {
                        $sendgrid_response_data = ['error' => $e->getMessage()];
                    }
                }
            }
        } elseif (class_exists('STW\Email\SendGrid')) {
            $store_data = Store();
            if ($store_data && method_exists($store_data, 'send_as_email')) {
                $res = \STW\Email\SendGrid::sendEmail(
                    $store_data->send_as_email, 
                    $store_data->name, 
                    $admin_email, 
                    $template_id, 
                    $form_details
                );
                
                // Store response for JavaScript output
                if ($res) {
                    try {
                        $status_code = method_exists($res, 'statusCode') ? $res->statusCode() : null;
                        $response_body = method_exists($res, 'body') ? $res->body() : null;
                        $sendgrid_response_data = [
                            'status_code' => $status_code,
                            'body' => $response_body,
                            'from' => $store_data->send_as_email,
                            'to' => $admin_email,
                            'template_id' => $template_id
                        ];
                    } catch (\Exception $e) {
                        $sendgrid_response_data = ['error' => $e->getMessage()];
                    }
                }
            }
        }
    }
    
    // Store SendGrid response and output to console
    if ($sendgrid_response_data) {
        gform_update_meta($entry_id, 'sendgrid_response', json_encode($sendgrid_response_data));
        
        // Add JavaScript to output console log via Gravity Forms confirmation filter
        add_filter('gform_confirmation_' . $form_id, function($confirmation, $form, $entry) use ($sendgrid_response_data) {
            $js_data = json_encode($sendgrid_response_data);
            $script = '<script>
                console.log("SendGrid Email Response:", ' . $js_data . ');
                // Also listen for AJAX confirmations
                if (typeof jQuery !== "undefined") {
                    jQuery(document).on("gform_confirmation_loaded", function(event, formId) {
                        if (formId == ' . $form['id'] . ') {
                            console.log("SendGrid Email Response:", ' . $js_data . ');
                        }
                    });
                }
            </script>';
            return $confirmation . $script;
        }, 10, 3);
    }
    
    // Build HTML email content
    $html = '<h1>New Anchor Up Website Onboarding</h1>';
    $html .= '<h2>View This New Entry in Airtables</h2>';
    $html .= '<p>A new store has onboarded for Connection Plus. Please check the Connection Plus Dashboard for more details.</p>';
    $html .= '<p>Store Name: ' . esc_html(rgar($entry, '4')) . '</p>';
    $html .= '<p>Store URL: ' . esc_html(rgar($entry, '1')) . '</p>';
    $html .= '<p>Anchor Customer ID: ' . esc_html(rgar($entry, '3')) . '</p>';
    $html .= '<p>Store Association: ' . esc_html(rgar($entry, '5')) . '</p>';
    $html .= '<p>POS System: ' . esc_html(rgar($entry, '42')) . '</p>';
    $html .= '<p>POS Notes: ' . esc_html(rgar($entry, '43')) . '</p>';
    $html .= '<p>Account First Name: ' . esc_html(rgar($entry, '6')) . '</p>';
    $html .= '<p>Account Last Name: ' . esc_html(rgar($entry, '7')) . '</p>';
    $html .= '<p>Store In Store Phone Number: ' . esc_html(rgar($entry, '9')) . '</p>';
    $html .= '<p>Store Street Address: ' . esc_html(rgar($entry, '18.1')) . '</p>';
    $html .= '<p>Store Street Address 2: ' . esc_html(rgar($entry, '18.2')) . '</p>';
    $html .= '<p>Store City: ' . esc_html(rgar($entry, '18.3')) . '</p>';
    $html .= '<p>Store State: ' . esc_html(rgar($entry, '18.4')) . '</p>';
    $html .= '<p>Store Zipcode: ' . esc_html(rgar($entry, '18.5')) . '</p>';
    $html .= '<p>Admin Email: ' . esc_html(rgar($entry, '19')) . '</p>';
    $html .= '<p>Support Email: ' . esc_html(rgar($entry, '21')) . '</p>';
    $html .= '<p>Webmaster - Contact for DNS: ' . esc_html(rgar($entry, '22')) . '</p>';
    $html .= '<p>Primary Theme Color: ' . esc_html(rgar($entry, '40')) . '</p>';
    $html .= '<p>Accent Theme Color: ' . esc_html(rgar($entry, '41')) . '</p>';
    $html .= '<p>Logo URL: ' . esc_html(rgar($entry, '25')) . '</p>';
    $html .= '<p>Paperwork Logo URL: ' . esc_html(rgar($entry, '26')) . '</p>';
    $html .= '<p>Address Label Logo URL: ' . esc_html(rgar($entry, '27')) . '</p>';
    $html .= '<p>Store Hours: ' . esc_html(rgar($entry, '28')) . '</p>';
    $html .= '<p>Store About Us Description: ' . esc_html(rgar($entry, '31')) . '</p>';
    $html .= '<p>Store Exterior Image URL: ' . esc_html(rgar($entry, '29')) . '</p>';
    $html .= '<p>Store Interior Image URL: ' . esc_html(rgar($entry, '30')) . '</p>';
    $html .= '<p>Store Short Intro: ' . esc_html(rgar($entry, '32')) . '</p>';
    $html .= '<p>Store Tagline: ' . esc_html(rgar($entry, '34')) . '</p>';
    $html .= '<p>In Store Services: ' . esc_html(rgar($entry, '33')) . '</p>';
    $html .= '<p>Store Facebook URL: ' . esc_html(rgar($entry, '35')) . '</p>';
    $html .= '<p>Store Instagram Username: ' . esc_html(rgar($entry, '36')) . '</p>';
    $html .= '<p>Store Twitter Username: ' . esc_html(rgar($entry, '37')) . '</p>';
    $html .= '<p>Store Covid Notice: ' . esc_html(rgar($entry, '38')) . '</p>';
    $html .= '<p>Store Additional Information: ' . esc_html(rgar($entry, '39')) . '</p>';
    
    $admin_emails = [
        'anchorup@anchordistributors.com',
        'scott.whitaker@anchordistributors.com',
        'customercare@anchordistributors.com'
    ];
    
    // Set email content type to HTML
    add_filter('wp_mail_content_type', function ($content_type) {
        return 'text/html';
    });
    
    // Send emails to admin addresses
    foreach ($admin_emails as $email) {
        wp_mail($email, 'Anchor Up Website - Onboarding - ' . esc_html(rgar($entry, '4')), $html);
    }
    
    // Remove the content type filter after sending
    remove_filter('wp_mail_content_type', function ($content_type) {
        return 'text/html';
    });
    
    // Clear Airtable cache if needed
    delete_option('_transient_stw.airtable.connection_plus');
}

// Auto-create registration pages and assign templates
add_action('admin_init', 'anchor_up_promotion_auto_create_registration_pages');
function anchor_up_promotion_auto_create_registration_pages() {
    // Only run once per day to avoid performance issues
    $last_check = get_option('anchor_up_registration_pages_last_check', 0);
    $current_time = time();
    
    // Check once per day
    if (($current_time - $last_check) < 86400) {
        return;
    }
    
    update_option('anchor_up_registration_pages_last_check', $current_time);
    
    // Define pages to create
    $pages_to_create = [
        [
            'title' => 'Anchor Up Promotion Registration',
            'slug' => 'anchor-up-promotion-registration',
            'template' => 'single-anchor-up-promotion-registration.php',
            'template_name' => 'Single Anchor Up Promotion Registration'
        ],
        [
            'title' => 'Anchor Up Website Registration',
            'slug' => 'anchor-up-website-registration',
            'template' => 'single-anchor-up-website-registration.php',
            'template_name' => 'Single Anchor Up Website Registration'
        ]
    ];
    
    foreach ($pages_to_create as $page_data) {
        // Check if page with this template already exists
        $existing_page = get_posts([
            'post_type' => 'page',
            'post_status' => ['publish', 'draft', 'private'],
            'meta_key' => '_wp_page_template',
            'meta_value' => $page_data['template'],
            'posts_per_page' => 1,
            'fields' => 'ids'
        ]);
        
        // If page doesn't exist, create it
        if (empty($existing_page)) {
            // Also check by slug to avoid duplicates
            $page_by_slug = get_page_by_path($page_data['slug']);
            
            if (!$page_by_slug) {
                $page_id = wp_insert_post([
                    'post_title' => $page_data['title'],
                    'post_name' => $page_data['slug'],
                    'post_status' => 'publish',
                    'post_type' => 'page',
                    'post_content' => '',
                    'meta_input' => [
                        '_wp_page_template' => $page_data['template']
                    ]
                ]);
                
                if (!is_wp_error($page_id) && $page_id) {
                    // Ensure template is set correctly
                    update_post_meta($page_id, '_wp_page_template', $page_data['template']);
                }
            } else {
                // Page exists but doesn't have the template - update it
                update_post_meta($page_by_slug->ID, '_wp_page_template', $page_data['template']);
            }
        } else {
            // Page exists with template - make sure it's published
            $page_id = $existing_page[0];
            $page = get_post($page_id);
            if ($page && $page->post_status !== 'publish') {
                wp_update_post([
                    'ID' => $page_id,
                    'post_status' => 'publish'
                ]);
            }
        }
    }
}

// Enqueue admin script for dynamic sign-up counter updates
add_action('admin_footer', 'anchor_up_promotion_enqueue_signup_counter_script');
function anchor_up_promotion_enqueue_signup_counter_script() {
    $screen = get_current_screen();
    
    // Only load on anchor-up-promotion post list page
    if ($screen && $screen->post_type === 'anchor-up-promotion' && $screen->base === 'edit') {
        ?>
        <script type="text/javascript">
        (function($) {
            'use strict';
            
            // Function to update sign-up counter for a specific promotion
            function updateSignupCounter(postId, counterElement) {
                $.ajax({
                    url: ajaxurl,
                    type: 'POST',
                    data: {
                        action: 'anchor_up_get_signup_count',
                        post_id: postId,
                        nonce: '<?php echo wp_create_nonce('anchor_up_signup_count_nonce'); ?>'
                    },
                    success: function(response) {
                        if (response.success && response.data) {
                            var data = response.data;
                            var maxKits = data.max_kits || 0;
                            var signUpsCount = data.sign_ups_count || 0;
                            var remaining = maxKits - signUpsCount;
                            
                            if (maxKits > 0) {
                                var percentage = (signUpsCount / maxKits) * 100;
                                percentage = Math.min(100, Math.max(0, percentage));
                                
                                // Color coding
                                var color, status;
                                if (remaining <= 0) {
                                    color = '#ef4444';
                                    status = 'Sold Out';
                                } else if (remaining <= (maxKits * 0.1)) {
                                    color = '#f59e0b';
                                    status = 'Low Stock';
                                } else {
                                    color = '#10b981';
                                    status = 'Available';
                                }
                                
                                // Update the counter element
                                var html = '<div style="font-weight: 600; font-size: 14px; margin-bottom: 4px;">' +
                                    '<span style="color: ' + color + ';">' + signUpsCount + ' / ' + maxKits + '</span>' +
                                    '</div>' +
                                    '<div style="font-size: 11px; color: #6b7280; margin-bottom: 4px;">' +
                                    '<span style="color: ' + color + ';">● ' + status + '</span>' +
                                    ' <span style="color: #9ca3af;">(' + remaining + ' remaining)</span>' +
                                    '</div>' +
                                    '<div style="width: 100%; background: #e5e7eb; height: 6px; border-radius: 3px; overflow: hidden; margin-top: 4px;">' +
                                    '<div style="background: ' + color + '; height: 100%; width: ' + percentage + '%; transition: width 0.3s ease;"></div>' +
                                    '</div>';
                                
                                counterElement.html(html);
                            }
                        }
                    },
                    error: function() {
                        console.error('Failed to update sign-up counter for post ID: ' + postId);
                    }
                });
            }
            
            // Update all counters on page load
            function updateAllCounters() {
                $('.signup-counter').each(function() {
                    var $counter = $(this);
                    var postId = $counter.data('post-id');
                    if (postId) {
                        updateSignupCounter(postId, $counter);
                    }
                });
            }
            
            // Update counters when page loads
            $(document).ready(function() {
                updateAllCounters();
                
                // Update every 30 seconds
                setInterval(updateAllCounters, 30000);
                
                // Update when window regains focus
                $(window).on('focus', function() {
                    updateAllCounters();
                });
            });
            
            // Update counter after a new sign-up is created (listen for post updates)
            $(document).on('DOMNodeInserted', function(e) {
                if ($(e.target).hasClass('signup-counter') || $(e.target).find('.signup-counter').length) {
                    updateAllCounters();
                }
            });
            
        })(jQuery);
        </script>
        <?php
    }
}

// AJAX handler to get sign-up count
add_action('wp_ajax_anchor_up_get_signup_count', 'anchor_up_promotion_ajax_get_signup_count');
function anchor_up_promotion_ajax_get_signup_count() {
    // Verify nonce
    if (!isset($_POST['nonce']) || !wp_verify_nonce($_POST['nonce'], 'anchor_up_signup_count_nonce')) {
        wp_send_json_error(array('message' => 'Invalid nonce'));
        return;
    }
    
    $post_id = isset($_POST['post_id']) ? intval($_POST['post_id']) : 0;
    
    if (!$post_id) {
        wp_send_json_error(array('message' => 'Invalid post ID'));
        return;
    }
    
    $max_kits = get_field('max_numbers_of_kits', $post_id);
    $max_kits = $max_kits ? intval($max_kits) : 0;
    
    // Count sign-ups for this promotion
    $sign_ups_query = new WP_Query(array(
        'post_type' => 'promo-signup',
        'posts_per_page' => -1,
        'meta_query' => array(
            array(
                'key' => 'specific_signup_promotion_relationship',
                'value' => $post_id,
                'compare' => '=',
            ),
        ),
        'fields' => 'ids',
    ));
    
    $sign_ups_count = $sign_ups_query->found_posts;
    
    wp_reset_postdata();
    
    wp_send_json_success(array(
        'max_kits' => $max_kits,
        'sign_ups_count' => $sign_ups_count,
        'remaining' => $max_kits - $sign_ups_count
    ));
}

// REST API endpoint for LCB Hero Banner
add_action('rest_api_init', 'anchor_up_promotion_register_lcb_hero_banner_endpoint');
function anchor_up_promotion_register_lcb_hero_banner_endpoint() {
    register_rest_route('stw/v1', '/lcb-hero-banner', array(
        'methods' => 'GET',
        'callback' => 'anchor_up_promotion_get_lcb_hero_banner',
        'permission_callback' => '__return_true', // Public endpoint
        'args' => array(
            'date' => array(
                'description' => 'Optional date for testing (format: Y-m-d)',
                'type' => 'string',
                'validate_callback' => function($param, $request, $key) {
                    return empty($param) || preg_match('/^\d{4}-\d{2}-\d{2}$/', $param);
                }
            ),
            'debug' => array(
                'description' => 'Enable debug mode to see detailed information',
                'type' => 'boolean',
                'default' => false,
            ),
        ),
    ));
}

function anchor_up_promotion_get_lcb_hero_banner($request) {
    // Get date from request parameter (for testing) or use current date
    $test_date = $request->get_param('date');
    $check_date = $test_date ? $test_date : date('Y-m-d');
    $check_timestamp = strtotime($check_date);
    $debug_mode = $request->get_param('debug') === true || $request->get_param('debug') === 'true' || $request->get_param('debug') === '1';
    
    if (!$check_timestamp) {
        return new WP_Error('invalid_date', 'Invalid date format. Use Y-m-d format.', array('status' => 400));
    }
    
    $debug_info = array();
    
    // Query all published anchor-up-promotion posts
    $promotions = get_posts(array(
        'post_type' => 'anchor-up-promotion',
        'post_status' => 'publish',
        'posts_per_page' => -1,
        'orderby' => 'meta_value',
        'meta_key' => 'marketing_to_anchor_up_stores_start_date',
        'order' => 'DESC',
        'meta_query' => array(
            'relation' => 'OR',
            array(
                'key' => 'marketing_to_anchor_up_stores_start_date',
                'compare' => 'EXISTS',
            ),
            array(
                'key' => 'promotion_start_date',
                'compare' => 'EXISTS',
            ),
        ),
    ));
    
    $active_banner = null;
    $active_start_date = null;
    $active_end_date = null;
    
    if ($debug_mode) {
        $debug_info['total_promotions'] = count($promotions);
        $debug_info['check_date'] = $check_date;
        $debug_info['check_timestamp'] = $check_timestamp;
        $debug_info['promotions_checked'] = array();
    }
    
    // Loop through promotions to find one with active date range
    foreach ($promotions as $promotion) {
        $post_id = $promotion->ID;
        
        // Get date fields - try raw meta first (stored as Ymd format), fallback to get_field()
        // ACF stores dates in Ymd format in the database, but get_field() returns formatted dates
        $marketing_start_date_raw = get_post_meta($post_id, 'marketing_to_anchor_up_stores_start_date', true);
        $promotion_start_date_raw = get_post_meta($post_id, 'promotion_start_date', true);
        $promotion_end_date_raw = get_post_meta($post_id, 'promotion_end_date', true);
        
        // If raw meta is empty, try get_field() as fallback (might be formatted)
        if (empty($marketing_start_date_raw)) {
            $marketing_start_date_raw = get_field('marketing_to_anchor_up_stores_start_date', $post_id);
        }
        if (empty($promotion_start_date_raw)) {
            $promotion_start_date_raw = get_field('promotion_start_date', $post_id);
        }
        if (empty($promotion_end_date_raw)) {
            $promotion_end_date_raw = get_field('promotion_end_date', $post_id);
        }
        
        $hero_banner = get_field('local_christian_bookstore_com_hero_banner_during_promotion_period', $post_id);
        
        if ($debug_mode) {
            $promo_debug = array(
                'post_id' => $post_id,
                'post_title' => get_the_title($post_id),
                'marketing_start_date_raw' => $marketing_start_date_raw,
                'promotion_start_date_raw' => $promotion_start_date_raw,
                'promotion_end_date_raw' => $promotion_end_date_raw,
                'has_banner' => !empty($hero_banner),
            );
        }
        
        // Skip if no banner image
        if (empty($hero_banner)) {
            continue;
        }
        
        // Determine start date - prefer marketing_start_date, fallback to promotion_start_date
        $start_date_raw = $marketing_start_date_raw ? $marketing_start_date_raw : $promotion_start_date_raw;
        
        // Skip if we don't have both start and end dates
        if (empty($start_date_raw) || empty($promotion_end_date_raw)) {
            continue;
        }
        
        // Convert dates to timestamps
        // ACF stores dates in Ymd format (e.g., 20251219)
        // Convert to timestamp for comparison
        $start_timestamp = false;
        $end_timestamp = false;
        
        // Parse start date - ACF stores as Ymd (8 digits, e.g., 20251219)
        if (preg_match('/^\d{8}$/', $start_date_raw)) {
            // Format: Ymd (e.g., 20251219) - convert to Y-m-d for strtotime
            $year = substr($start_date_raw, 0, 4);
            $month = substr($start_date_raw, 4, 2);
            $day = substr($start_date_raw, 6, 2);
            $start_timestamp = strtotime($year . '-' . $month . '-' . $day);
        } else {
            // Try parsing as formatted date string (fallback - from get_field())
            $start_timestamp = strtotime($start_date_raw);
            if (!$start_timestamp) {
                // Try cleaning up the date string
                $start_date_clean = str_replace(array('/', ','), array('-', ''), $start_date_raw);
                $start_timestamp = strtotime($start_date_clean);
            }
        }
        
        // Parse end date - ACF stores as Ymd (8 digits, e.g., 20251219)
        if (preg_match('/^\d{8}$/', $promotion_end_date_raw)) {
            // Format: Ymd (e.g., 20251219) - convert to Y-m-d for strtotime
            $year = substr($promotion_end_date_raw, 0, 4);
            $month = substr($promotion_end_date_raw, 4, 2);
            $day = substr($promotion_end_date_raw, 6, 2);
            $end_timestamp = strtotime($year . '-' . $month . '-' . $day);
        } else {
            // Try parsing as formatted date string (fallback - from get_field())
            $end_timestamp = strtotime($promotion_end_date_raw);
            if (!$end_timestamp) {
                // Try cleaning up the date string
                $end_date_clean = str_replace(array('/', ','), array('-', ''), $promotion_end_date_raw);
                $end_timestamp = strtotime($end_date_clean);
            }
        }
        
        // Skip if we still can't parse dates
        if (!$start_timestamp || !$end_timestamp) {
            // Log for debugging (only if WP_DEBUG is enabled)
            if (defined('WP_DEBUG') && WP_DEBUG) {
                error_log(sprintf(
                    'Anchor Up Promotion: Could not parse dates for post ID %d. Start (raw): %s, End (raw): %s',
                    $post_id,
                    $start_date_raw,
                    $promotion_end_date_raw
                ));
            }
            if ($debug_mode) {
                $promo_debug['date_parsing_failed'] = true;
                $promo_debug['start_timestamp'] = $start_timestamp;
                $promo_debug['end_timestamp'] = $end_timestamp;
                $debug_info['promotions_checked'][] = $promo_debug;
            }
            continue;
        }
        
        if ($debug_mode) {
            $promo_debug['start_timestamp'] = $start_timestamp;
            $promo_debug['end_timestamp'] = $end_timestamp;
            $promo_debug['start_date_formatted'] = date('Y-m-d', $start_timestamp);
            $promo_debug['end_date_formatted'] = date('Y-m-d', $end_timestamp);
            $promo_debug['check_timestamp'] = $check_timestamp;
            $promo_debug['is_within_range'] = ($check_timestamp >= $start_timestamp && $check_timestamp <= $end_timestamp);
        }
        
        // Check if check_date falls within the date range (inclusive)
        if ($check_timestamp >= $start_timestamp && $check_timestamp <= $end_timestamp) {
            // Handle different ACF image return formats
            $banner_url = '';
            if (is_string($hero_banner)) {
                // Already a URL
                $banner_url = $hero_banner;
            } elseif (is_array($hero_banner)) {
                // Array format - get URL
                $banner_url = isset($hero_banner['url']) ? $hero_banner['url'] : (isset($hero_banner['sizes']['full']) ? $hero_banner['sizes']['full'] : '');
            } elseif (is_numeric($hero_banner)) {
                // Image ID - get URL
                $banner_url = wp_get_attachment_image_url($hero_banner, 'full');
            }
            
            if (!empty($banner_url)) {
                $active_banner = $banner_url;
                $active_start_date = date('Y-m-d', $start_timestamp);
                $active_end_date = date('Y-m-d', $end_timestamp);
                if ($debug_mode) {
                    $promo_debug['matched'] = true;
                    $promo_debug['banner_url'] = $banner_url;
                    $debug_info['promotions_checked'][] = $promo_debug;
                }
                break; // Use first matching promotion
            }
        }
        
        if ($debug_mode && !isset($promo_debug['matched'])) {
            $debug_info['promotions_checked'][] = $promo_debug;
        }
    }
    
    // Return response
    $response_data = array(
        'success' => true,
        'banner_url' => $active_banner,
        'start_date' => $active_start_date,
        'end_date' => $active_end_date,
        'check_date' => $check_date,
    );
    
    if ($debug_mode) {
        $response_data['debug'] = $debug_info;
    }
    
    if ($active_banner) {
        return new WP_REST_Response($response_data, 200);
    } else {
        // Check for default banner on options page
        $default_banner = get_field('default_background_image_lcb', 'option');
        $default_banner_url = '';
        
        if (!empty($default_banner)) {
            // Handle different ACF image return formats
            if (is_string($default_banner)) {
                $default_banner_url = $default_banner;
            } elseif (is_array($default_banner)) {
                $default_banner_url = isset($default_banner['url']) ? $default_banner['url'] : (isset($default_banner['sizes']['full']) ? $default_banner['sizes']['full'] : '');
            } elseif (is_numeric($default_banner)) {
                $default_banner_url = wp_get_attachment_image_url($default_banner, 'full');
            }
        }
        
        // Return success with default banner or null
        $response_data = array(
            'success' => true,
            'banner_url' => $default_banner_url ?: null,
            'start_date' => null,
            'end_date' => null,
            'check_date' => $check_date,
            'message' => $default_banner_url ? 'Using default banner (no active promotion found).' : 'No active promotion banner or default banner found for the specified date.',
        );
        
        if ($debug_mode) {
            $response_data['debug'] = $debug_info;
        }
        
        return new WP_REST_Response($response_data, 200);
    }
}

